### PR TITLE
Add Smux to VLESS

### PR DESCRIPTION
**Pull request by ccpmostwanted**
Added [Smux](https://github.com/xtaci/smux) package to VLESS protocol. 

Updates in this PR:
- Smux only needs to be enabled on the client side, with 1 additional JSON property "smux",
```
"vnext": [
  {
    "address": address,
    "port": port,
    "smux": true,
    "users": [
      {
        "id": id
        "encryption": "none",
        "level": 0
      }
    ]
  }
]
```
At the moment , the Smux option ONLY works with VLESS protocol and DOES NOT work with VLESS + XTLS(should work with TLS)
- Added a new VLESS command **protocol.RequestCommandSmux(0x04)** so that the smux option only has to be enabled on client side. The server can adapt to that by checking the VLESS command byte.
- Modified the inbound/outbound handler under /proxy/vless/ to handle Smux request.
- Encapsulated VLESS and Simplesocks connections into classes.
- From top to bottom the architecture of Smux functionality is Simplesocks -> Smux -> VLESS -> TCP.

TODOs:
- XTLS should work with some tweaking inside the VLESS handler
- Needs a better mechanism to manage existing connections.(Health checking of existing connections)
- Smux manager should be able to hold multiple concurrent connections instead of just 1, and dispatch them through round-robin

### CODE REVIEW

**Comment by rprx** [comment]
先感谢 PR

**Comment by Fhokud** [comment]
能不能有类似mux的concurrency指定连接复用数量

**Comment by ccpmostwanted** [comment]
Update:

1. SmuxManager allows up to 8 concurrent connections
2. Wrap VLESS header processing inside Inbound/Outbound connection

TODO: 
I tried to put all the VLESS header processing logic inside the Inbound/Outbound connection struct so that the VLESS handler functions look nice and clean. XTLS works for the most part except for **xtls-rprx-splice** as I don't quite understand how ReadV works.

**Comment by rprx** [comment]
可以先加到 Trojan 吗，我打算修一下现有的 Mux

**Comment by ccpmostwanted** [comment]
> 
> 
> 可以先加到 Trojan 吗，我打算修一下现有的 Mux

请问Mux修复的怎么样了，如果mux可以修好的话我觉得就不用加smux了

**Pull request closed without merging**
