### PR TITLE
splithttp transport

### PR DESCRIPTION
**Pull request by mmmray**
**how it works:**

* each transported stream is identified by a random UUID `<uuid>`
* download using long-living chunked-transfer from `GET /?session=<uuid>`
* upload using `POST /?session=<uuid>`

**personal design goals:**

* see #2162 #3334 for extended motivation
* transport that can pass more CDNs, CDN does not have to support websocket
* support of not only CDNs, but anything that can proxy HTTP
* someday, in the future: ability to split up/download to different CDN (without dialerProxy/loopback tricks)
* simpler than meek

**implementation notes, concerns:**

* putting session ID in URL achieves two goals: cache-busting, and avoiding requirement that the HTTP proxy forwards HTTP headers correctly. this can be debated.

* no decoupling of connection lifetime from inner stream lifetime. particularly, CDNs may enforce a total response timeout, which would affect connection quality.

  on the other hand, this makes it easier to prevent DoS attacks: the in-memory map for storing sessions is always bounded by the number of physical TCP connections

* connection upload can be hijacked **without active MITM**, by reading the UUID passively and using it from another machine. I don't think this is a practical issue, the answer is always to use TLS in any case.

* i noticed a lot of HTTP-ish transports write to the socket directly. However, I need HTTP connection reuse for performance, so I want to use http.Client.

* I have a lot of trouble getting `http.Client` to work correctly with uTLS. as a result, ALPN protocol negotiation is not correctly implemented, and HTTP2 prior knowledge is assumed for https://. For http://, HTTP/1.1 is used anyway.

**usage notes:**

On server and client:

```
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "host": "example.com",
          "path": "/"
        }
      }
```

* if the connection hangs, most likely the CDN is buffering the response body of `GET`. i found that nginx and apache respond to `X-Accel-Buffering: no` response header and disable buffering.

### CODE REVIEW

**Comment by Fangliding** [comment]
How many tested CDNs?

**Comment by irgfw** [comment]
In theory, this could solve many problems in Iran.

**Comment by Fangliding** [comment]
@mmmray Don't mind about the test fail, it's sometimes like this, it's not your problem((((

**Comment by yuhan6665** [comment]
Thanks for your great work @mmmray !
@Fangliding I've been improving xray's test for a long time. I'm 99.9% sure the test failure are caused by your test. I notice sometimes Test_listenSHAndDial fail and sometimes Test_listenWSAndDial fail. Maybe they share something in common and it is due to run them in parallel? Please help to fix it
@RPRX please take a look before we can merge

**Comment by yuhan6665** [comment]
lol that is fast @mmmray

**Comment by yuhan6665** [comment]
> it seems that the tests actually fail because they attempt to use the same ports as the websocket tests, while running concurrently with them
> 
> `testing.servers.tcp.port.PickPort` appears to be the correct solution (used in http2 transport), but the implementation is broken for me on Ubuntu. It is missing SO_REUSEPORT, but the implementation of that is platform-specific.
> 
> I will hardcode different port numbers, but I wonder if pulling in another dependency [go-reuseport](https://github.com/libp2p/go-reuseport) is ok for testing?

The idea of PickPort() is that it tries to listen a port, and then quickly release self and pass this port number to the user. It is a simple yet proven solution. I highly recommend it over magic like SO_REUSEPORT ;)

**Comment by RPRX** [comment]
非常感谢 PR！我觉得实现这样的传输层，最大的挑战在于 **客户端的请求不一定会按顺序到达服务端**，有针对这种情况做处理吗？

**Comment by RPRX** [comment]
另外目前对于 h2 的情况是一个连接占一条 h2 还是多个连接复用同一条 h2

**Comment by RPRX** [comment]
> > may not necessarily arrive at the server in order . Is there any handling for this situation?
> 
> the start of one HTTP request is hard-blocked on the successful 200 OK response of the previous data chunk. basically, there is a single `for { .. }` goroutine in `dialer.go` that sends http requests synchronously.

这样处理比较简单，但效率非常低，且无法应对实时性要求比较高的应用，实用性会打折扣，试试实现一个序号与服务端缓存机制

（不过对于 h1 好像只能是现在这样）

> > is one connection occupying one h2 or multiple connections reuse the same h2?
> 
> ah, currently there is one entire `http.Client` per connection. this could be improved, but I am not sure if there is another way than global `sync.Map`? I think the `http.Client` would have to be created per-outbound somehow.

目前是你说的那种处理方式的话确实无法多个连接复用同一条 h2，换成我说的那种方式的话可以，代码参考 h2 transport

**Comment by RPRX** [comment]
比如说你可以让同一个连接用一个共同的 UUID 再加上序号，0 代表下行，1 2 3 4 5... 代表上行，一直发，不用等服务端返回 200

**Comment by RPRX** [comment]
> Reducing the bandwidth overhead

不是为了这件事，而是客户端要等服务端回复后再发第二个包的话，会造成高延迟和低带宽，所以 TCP 不会等 ACK 再发第二个包

**Comment by RPRX** [comment]
> > For the code, please refer to h2 transport.
> 
> Ah, I see. I'm new to Go, so I didn't really understand how [things like this](https://github.com/mmmray/Xray-core/blob/344d4f442187fd4f547eafbb9e0035d10e17ae91/transport/internet/memory_settings.go#L6) can be used as map keys. I will just copy it.

好像找错地方了，相关代码在 [这里](https://github.com/XTLS/Xray-core/blob/main/transport/internet/http/dialer.go)，查看 `globalDialerMap`

**Comment by RPRX** [comment]
```go
type dialerConf struct {
	net.Destination
	*internet.MemoryStreamConfig
}
```

其实 `*internet.MemoryStreamConfig` 就是个指针，用于区分不同的出站，这里应该是只对比了指针本身，没有深层对比

比如说两个出站的配置一样，但指针肯定不一样，还是会被认定为两个出站，~~深层对比的话认定为同一个出站就不好了~~

**Comment by Fangliding** [comment]
> Thanks for your great work @mmmray ! @Fangliding I've been improving xray's test for a long time. I'm 99.9% sure the test failure are caused by your test. I notice sometimes Test_listenSHAndDial fail and sometimes Test_listenWSAndDial fail. Maybe they share something in common and it is due to run them in parallel? Please help to fix it @RPRX please take a look before we can merge

I have run a single test file several times on my own device without any issues. I forgot that using the same port may cause them to fight 🙈

**Comment by RPRX** [comment]
> I have run a single test file several times on my own device without any issues. I forgot that using the same port may cause them to fight 🙈

正想说这件事，单独 PR 一下 ws_test.go 吧

**Comment by yuhan6665** [comment]
I think it is test file compilation issue. You can see in the test action page

>  transport/internet/websocket/ws_test.go#L124
> no new variables on left side of :=

**Comment by Fangliding** [comment]
Did you tried to set a timeout in http.client
```
&http.Client{
		Timeout:   time.Second * 180,
		Transport: httpTransport,
	}
```

**Comment by yuhan6665** [comment]
I can take a look at the utls and alpn implementation when I have time..

**Comment by RPRX** [comment]
@yuhan6665 v1.8.x 还是 v1.9.0

**Comment by yuhan6665** [comment]
感觉这个可以放1.8

**Comment by RPRX** [comment]
~~这下 v1.8.x 成 Xray-core stream 版了~~

**Comment by yuhan6665** [comment]
@mmmray I pulled in a quick implementation https://github.com/XTLS/Xray-core/commit/d9495331a1cb894808e895fbb0031c81be7c2ba0 maybe you can help to verify?

**Comment by RPRX** [comment]
在与 @yuhan6665 讨论后，ALPN 原有的逻辑已经足够，**即 TLS 默认 H2，非 TLS 默认 H1**，所以需要你把最新的 commit force 掉

因为正常来说 TLS 总是会协商出 H2，几乎没有支持 TLS 但不支持 H2 的 CDN，没有必要把这部分代码弄得过于复杂

此外，H1 目前有没有序号机制（想让它和 H2 对称）？它的 connection pooling 指的是上一条连接结束后下一条连接接着用吗？

**Comment by RPRX** [comment]
> My understanding is that `http.Transport` also has a connection pool, so it should work the same.

这样的话，由于 HTTP/1.1 不支持多路复用，所以我猜 Golang 为避免阻塞会同时建立很多连接，需要用 WireShark 确认一下行为

**Comment by RPRX** [comment]
> In order to reuse connections across downloads

我觉得对 HTTP/1.1 而言，即使原生做到了这一点，用于上行的 TCP 连接数还是太多，所以文档应当推荐始终启用 Xray 的 Mux

此外，目前 Xray 没有为 H2 自己的多路复用提供一些控制选项，比如 concurrency 和 max connections，还有这类：https://github.com/XTLS/Xray-core/discussions/3434
但是这些可以在以后的版本中为 H2、gRPC、SplitHTTP 一起加上，你可以研究一下

这个 PR 等下会被合并，然后先发个小版本让大家测试一下，感谢贡献！

**Comment by RPRX** [comment]
> the start of one HTTP request is hard-blocked on the successful 200 OK response of the previous data chunk

~~我被你之前说这个带偏了~~，才想起来正常的 HTTP/1.1 可以连续发送请求而不用等响应，这样的话用于上行的 TCP 连接可以很少

> I see in wireshark that the client does use a lot of concurrent tcp sessions to upload on speedtest

所以这件事就有点奇怪了

**Comment by RPRX** [comment]
> it uses `http.Client` which always reads response headers after writing

可以读取但不能阻塞下一个请求，否则需要被改变

> i think it is (theoretically) possible that it is perceived as attack by some servers

是有这种可能，还有可能服务端偶尔会漏收一两个数据，所以客户端需要新建协程来等待 response 并重发数据，比如最多 3 次

对于 H2 和 HTTP/1.1 都可以有这个机制，但是会有点占内存，服务端那个基于序号的缓存机制也是如此

**Comment by RPRX** [comment]
不过客户端这个重发机制是否有必要，需要实测，我觉得没被视作攻击时服务端基本上不会漏收数据，而被视作攻击时重发也没用

**Comment by RPRX** [comment]
~~我不熟悉 Golang 的这些库，但我觉得对于 HTTP/1.1 应该有方便的可并发且不阻塞的 request 方法吧，不然的确很 inelegant~~

**Comment by RPRX** [comment]
@yuhan6665 将那些信息转发给我了。我希望减少 HTTP/1.1 的连接数是因为 it's the right way to go，减少连接数不仅更优雅，还可以减少对资源的需求从而可以在更苛刻的条件下工作，当然还可能可以少吸引些来自 GFW 的注意。但如果这件事实在难以在短期内实现且伊朗人急需这个新 transport，我们可以先合并了这个 PR 并发一个新版本，@mmmray 你来决定。

**Comment by hawshemi** [comment]
> attract less attention from GFW

We guess one of the main reasons for Reality and all other VMESS/VLESS combinations blockage in Iran is this.

**Review by yuhan6665 — APPROVED** [review]
Looks good to me!

**Comment by RPRX** [comment]
LGTM 虽然我没有看代码 但是代码能跑就是好样的 这就发版+更新分享链接标准

不过 建议你在文档中写一下实现细节 方便其它软件实现这个 transport

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.15 https://github.com/XTLS/Xray-core/discussions/716

**Comment by RPRX** [comment]
看了 @mmmray 的文档和 @yuhan6665 的 release note 之后，我把新版标注为了 pre-release，有几个地方：

1. 据文档的“协议细节”所述，客户端会等到 GET 返回 200 后才发送上行数据，这会徒增 1-RTT，**此处需要修改为直接开始发**
2. “CDN必须禁用缓存, 或者缓存不忽略查询字符串”，这里需要一个 breaking change，把所有 `?` 都改为路径，即 POST `prefix/UUID/0`，这样的话 CDN 天然不会认为是同一个路径从而不会缓存，**就是说全用路径而不要用任何传参**
3. 文档中关于 ALPN 的“已知问题”是过期描述，**现在就是这么设计的，应该移到“协议细节”**
4. 文档中关于效率的问题，下行效率肯定拉满，需要标注，只是上行效率可能不如 WebSocket，但也不会差太多。@yuhan6665 提到了 meek 和 v2fly 的实现，就是说 SplitHTTP 和 meek 除了都能穿透不支持 WebSocket 的 CDN 外有什么很大的共同点吗？**SplitHTTP 是基于我提出的实现方式，实现细节也是我在这里说的，我没有仔细研究过 meek 且我相信 @mmmray 的实现没有参考过半点 v2fly 的 meek 代码，就是说可以给 credit 但不要乱给 credit，此外文档需要标注至少下行效率比 meek 更高**
5. 文档中有两处 WebSocket 需要改为 SplitHTTP

以上。

**Comment by RPRX** [comment]
我不认为现有的实现能够“prevent somebody from opening arbitrary amount of session IDs and never closing them”，毕竟 GET 也没有任何的鉴权，所以先把这个不必要的 1-RTT 减掉，防止恶意请求的逻辑我们可以放到以后的版本中再实现

此外把传参改成路径即可，还有文档照我说的修改即可（上行效率已经尽可能高了），希望我们能于明天发布下一个版本

**Comment by RPRX** [comment]
I believe HTTP/2 is our prior concern, and therefore the cost of attack is very low, considering our current code.

But, of course it's not bad to have "session TTL", and you have enough time to prepare the PR and doc fix. Just ASAP, thanks!

**Comment by RPRX** [comment]
> this is in ZH docs, need somebody else to do it

@Fangliding

**Comment by Fangliding** [comment]
是我瞎了 我看英文版本的时候意识到这是ws翻译过来的描述为了行文统一就去复制过来了没想到改漏了地方 我自己读了两三遍还没发现

**Comment by liushengqi000** [comment]
干得好，终于看到tcp拆成多个http的实现了。我只会把流量转成http3，然后把udp包在不同连接上乱发，反正一切都有http3来维护

**Pull request merged**
