### PR TITLE
Transport: Remove QUIC

### PR DESCRIPTION
**Pull request by mmmray**
The reasoning is that SplitHTTP+H3 is "good enough" in its current state. A later version of SplitHTTP may introduce a faster kind of upload (unlike QUIC transport, compatible with nginx), but personally it's not clear to me if there's demand.

### CODE REVIEW

**Comment by mmmray** [comment]
[validation requirements](https://github.com/XTLS/Xray-core/pull/3751#issuecomment-2323843248) are satisfied because `"network": "quic"` now throws an [error](https://github.com/mmmray/Xray-core/blob/558cfcc5072f438b735b6e4bfd88f20ca6093f95/infra/conf/transport_internet.go#L684)

the error message could be adjusted for better UX? :man_shrugging:

**Comment by RPRX** [comment]
Generally，我觉得 Xray 中的 QUIC 以后应当以“TLS/REALITY H3”选项的形式存在，可被多样组合，而不是像这个一样可组合性很差

**Comment by Yochee** [comment]
> Generally，我觉得 Xray 中的 QUIC 以后应当以“TLS/REALITY H3”选项的形式存在，可被多样组合，而不是像这个一样可组合性很差

蹲一个，最近ip经常被tcp阻断，目前能用splithttp+tls h3走udp苟活，但是感觉tls reality h3更好（没cdn需求且担心sni阻断的情况下）

**Comment by lolitakon** [comment]
Splithttp h3 is more compatible than the original quic in terms of concealment and high concurrency, but it also introduces more delays, and there are still some compatibility issues. I think it is necessary to temporarily restore the original quic stream until splithttp solves the compatibility and higher latency issues

**Comment by mrez-ir** [comment]
There is a demand my friend.. I've tested multiple protocols for IRAN network and QUIC was the best working one. I've moved to old versions of xray(v1.8.24) for fixing this problem(not supporting QUIC) in my case for now. But keeping different protocol options are very good because of different situations of country GFWs which are using deep packet inspection and many different AI tools to restrict, filter and monitorize our internet.

**Comment by RPRX** [comment]
@mrez-ir Use XHTTP H3

**Comment by mrez-ir** [comment]
> @mrez-ir Use XHTTP H3

As you mensioned already tried it again now.. Its not working in IRAN.. GFW is detecting this.. i don't know how

**Comment by RPRX** [comment]
> > @mrez-ir Use XHTTP H3
> 
> As you mensioned already tried it again now.. Its not working in IRAN.. GFW is detecting this.. i don't know how

我能想到的重要区别，比如，是因为 H3 有 SNI 吗

**Comment by mrez-ir** [comment]
> > > @mrez-ir Use XHTTP H3
> > 
> > 
> > As you mensioned already tried it again now.. Its not working in IRAN.. GFW is detecting this.. i don't know how
> 
> 我能想到的重要区别，比如，是因为 H3 有 SNI 吗

I really don't want to exit the main subject of this thread by talking too much, but FYI, none of the REALITY and XHTTP+SNI protocols working here (they are detected). But QUIC works. This is just my report if it helps developers, with my regards and thanks to your works.

**Comment by RPRX** [comment]
> I really don't want to exit the main subject of this thread by talking too much, but FYI, none of the REALITY and XHTTP+SNI protocols working here (they are detected). But QUIC works. This is just my report if it helps developers, with my regards and thanks to your works.

我觉得你提供的信息以及测试环境很重要，试一下申请 IP 证书再用 XHTTP（无 SNI），~~晚些时候还需要你测测 Vision Seed~~

**Comment by mrez-ir** [comment]
> > I really don't want to exit the main subject of this thread by talking too much, but FYI, none of the REALITY and XHTTP+SNI protocols working here (they are detected). But QUIC works. This is just my report if it helps developers, with my regards and thanks to your works.
> 
> 我觉得你提供的信息以及测试环境很重要，试一下申请 IP 证书再用 XHTTP（无 SNI），~晚些时候还需要你测测 Vision Seed~

Using the selfsigned ip address was good idea I never tried before, but now I tested it too, the result was same as dns setup (it was detected and blocked by GFW). My testing enviiornment is [MHSanaei/3x-ui](https://github.com/MHSanaei/3x-ui).

**Comment by RPRX** [comment]
> Using the selfsigned ip address was good idea I never tried before, but now I tested it too, the result was same as dns setup (it was detected and blocked by GFW). My testing enviiornment is [MHSanaei/3x-ui](https://github.com/MHSanaei/3x-ui).

不是让你用自签的，~~我也不知道你开没开 allowInsecure 也不确定 Xray 的 quic-go 有没有它~~，试试申请个免费的 IP 证书

~~顺便问一句，你是 http://ip 这种方式访问 3X-UI 吗~~

**Comment by mrez-ir** [comment]
My friend, I may have mistakes in my builds.. but if you have telegram I can give you full access to my linux server to create, modify x-ui connections and I check your build results if it works from here. here is my telegram ID: [@dmrez](https://t.me/dmrez)

**Comment by RPRX** [comment]
> My friend, I may have mistakes in my builds.. but if you have telegram I can give you full access to my linux server to create, modify x-ui connections and I check your build results if it works from here. here is my telegram ID: [@dmrez](https://t.me/dmrez)

请联系 @yuhan6665 

~~所以你是 http://ip 这种方式访问 3X-UI 吗~~

**Comment by mrez-ir** [comment]
> > My friend, I may have mistakes in my builds.. but if you have telegram I can give you full access to my linux server to create, modify x-ui connections and I check your build results if it works from here. here is my telegram ID: [@dmrez](https://t.me/dmrez)
> 
> 请联系 @yuhan6665
> 
> ~所以你是 http://ip 这种方式访问 3X-UI 吗~

Here is my installed panel address:
https://ish2.cdkeysell.com:1443/mjs/panel/inbounds
user:Admin
pw:asdf12

the last inbound connection i created was based on your suggestions: ID:22 Name":XHTTP H3"

I'll delete this message for security when you replied, because i could not find you on telegram.

**Comment by RPRX** [comment]
@mrez-ir ~~赶紧改个密码~~，联系 TG @yuhan6665

**Comment by mrez-ir** [comment]
> @mrez-ir ~赶紧改个密码~，联系 TG @yuhan6665

I think you sending wrong Telegram ID. It can not be found in my telegram search.

**Comment by RelaxStation** [comment]
Please bring back quic
It worked very well in IRAN
SplitHTTP does not work properly

**Comment by popularteam** [comment]
@mrez-ir @RelaxStation    Can quic be used to restore blocked servers to work in Iran? I've tried so many things, and they've failed.

**Comment by popularteam** [comment]
@RPRX  Vision Seed I can find Iranian users to help you test, I have Iranian users and blocked VPS, tried many protocols, all failed, only ws+tls+cdn is successful, I don't want to rely on CDN, so I want to find a better way.

**Comment by mrez-ir** [comment]
> @mrez-ir @RelaxStation Can quic be used to restore blocked servers to work in Iran? I've tried so many things, and they've failed.

Yes Quic protocol works in Iran, but its removed in latest xray versions. You need to install older versions of applications using old xray cores (older than version 1.8.5 if I remember) to be able to use Quic protocol.

**Comment by popularteam** [comment]
@mrez-ir Hello friend, thank you for your reply. I am very interested in this, the message I sent to you on Telegram. Looking forward to your reply.

**Pull request merged**
