### PR TITLE
Resolve conflicting change in DNS #309 #341

### PR DESCRIPTION
**Pull request by JimhHan**
Co-Authored-By: @yuhan6665

### CODE REVIEW

**Comment by yuhan6665** [comment]
SystemDialer init() 能 exported 吗？因为 AndroidLibXrayLite 那边会用到 0a387132f01b7eede70e3a3f09f6c29530b53e2d

**Comment by JimhHan** [comment]
好的

**Comment by rprx** [comment]
感谢 PR

**Comment by rprx** [comment]
@yuhan6665 v2rayNG 中的测试是否存在问题

**Comment by yuhan6665** [comment]
我测了一下 好像没啥问题

**Comment by rurirei** [comment]
what about make this variable Public? (v2fly/v2ray-core#698) https://github.com/XTLS/Xray-core/blob/d7cd71b74195a64b6617b6f0abc27fb2f8e5102d/core/context.go#L10

**Comment by eroxs** [comment]
I connect to the tls + ws or http + tcp configuration and everything looks good at first
But suddenly (maybe a few hours or minutes later) when I try to open a site in a browser, I get an error I can not find the DNS address.
This error is very weak in the Chrome browser (sometimes displayed but the site suddenly opens)
This is also true for applications that use domains.
You have to think and have a solution
This does not look good at all

**Comment by JimhHan** [comment]
@eroxs 
Thanks for your support. We have found a bug related to DoH, and fixed in 32713bcc0e5b624e5075afe0392429e3bbbcae2e .

You can find a pre-build binary [here](https://github.com/XTLS/Xray-core/actions/runs/661975352)

**Comment by eroxs** [comment]
How to fix in v2rayNG?

**Comment by rurirei** [comment]
@eroxs logs needed. do not enables Secure DNS in chrome. how do you configuration in v2rayng?

**Comment by eroxs** [comment]
I normally add the configuration At first everything is fine, but maybe after a while or ip operator changes, see couldn't find dns

**Comment by rurirei** [comment]
@eroxs as not related here. open a new issue please.

**Pull request merged**
