### PR TITLE
Add "tproxy" option

### PR DESCRIPTION
**Pull request by S-Mocking**
### Add "tproxy" option
Added the function of "MacOS" FreeBSD firewall traffic forwarding and resolving destination address
example:
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 1122,
      "protocol": "dokodemo-door",
      "tag": "dokodemo",
      "settings": {
        "network": "tcp",
        "followRedirect": true,
        "userLevel": 0
      },
      "streamSettings": {
        "sockopt": {
          "tproxy": "pf"
        }
      }
    }
  ]

### CODE REVIEW

**Comment by yuhan6665** [comment]
合了 感谢大佬

**Comment by yuhan6665** [comment]
Thanks @dyhkwong for pointing it out.
@S-Mocking 是我之前没仔细看 如果我没理解错的话 你只需要改略微修改这三个地方
https://github.com/XTLS/Xray-core/blob/59602db02dfedecc677382a9945bd282d43e214b/transport/internet/tcp/sockopt_freebsd.go#L1
https://github.com/XTLS/Xray-core/blob/59602db02dfedecc677382a9945bd282d43e214b/transport/internet/udp/hub_freebsd.go#L1
https://github.com/XTLS/Xray-core/blob/main/transport/internet/sockopt_darwin.go

然后使用 "tproxy": "redirect" 即可以支持 mac
其实我觉得 加不加额外的 "tproxy": "pf" 皆可 但是最好是把两个代码合并一下 能麻烦你再改改？

**Comment by S-Mocking** [comment]
我是考虑到freebsd 操作系统与mac可能存在差异，所以才没用修改[sockopt_darwin.go](https://github.com/XTLS/Xray-core/blob/main/transport/internet/sockopt_darwin.go)

**Comment by S-Mocking** [comment]
我重新修改下

**Pull request merged**
