### PR TITLE
Fix: RPC call causes xray panic problem using wrong account type

### PR DESCRIPTION
**Pull request by bestwishCT**
…protocol user in an inbound proxy. If inTag: "VMess-xxx", but the developer carelessly calls the add user method of vless or other protocols, such as xrayCtl.AddVlessUser(user), causing xray panic

### CODE REVIEW

**Comment by RPRX** [comment]
~~仅新版的问题还是？~~

**Comment by bestwishCT** [comment]
> ~仅新版的问题还是？~

all

**Comment by Fangliding** [comment]
We have our log system, please use `errors.New("message")`

**Comment by RPRX** [comment]
> > ~仅新版的问题还是？~
> 
> all

~~那放到 v24.9.30 吧~~

**Comment by bestwishCT** [comment]
> We have our log system, please use `errors.New("message")`

ok

**Comment by RPRX** [comment]
> …protocol user in an inbound proxy. If inTag: "VMess-xxx", but the developer carelessly calls the add user method of vless or other protocols, such as xrayCtl.AddVlessUser(user), causing xray panic

~~看了描述才发现这甚至不能算是 bug，吓我一跳，真不想弄个 v1.8.25 出来~~

**Comment by bestwishCT** [comment]
> > …protocol user in an inbound proxy. If inTag: "VMess-xxx", but the developer carelessly calls the add user method of vless or other protocols, such as xrayCtl.AddVlessUser(user), causing xray panic
> 
> ~看了描述才发现这甚至不能算是 bug，吓我一跳，真不想弄个 v1.8.25 出来~

应该算吧   rpc调用直接把xray搞挂了  哈哈哈

**Comment by RPRX** [comment]
我看了下这个是只改了 VMess 的代码，VLESS 的不用改？

**Comment by yuhan6665** [comment]
This fix is optional, the main issue is with caller code.
Guys, please don't drag long review of simple fixes. Move fast and break things!

**Comment by RPRX** [comment]
> This fix is optional, the main issue is with caller code. Guys, please don't drag long review of simple fixes. Move fast and break things!

~~所以 VLESS 的怎么说~~

**Comment by bestwishCT** [comment]
Please delete my commit message



发自我的iPhone


------------------ Original ------------------
From: RPRX ***@***.***&gt;
Date: Sun,Sep 15,2024 11:52 AM
To: XTLS/Xray-core ***@***.***&gt;
Cc: bob ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [XTLS/Xray-core] Fix: RPC call causes xray panic problem usingwrong account type (PR #3744)





  
This fix is optional, the main issue is with caller code. Guys, please don't drag long review of simple fixes. Move fast and break things!
  
所以 VLESS 的怎么说

**Comment by RPRX** [comment]
> Please delete my commit message

@yuhan6665 说你可能是想删掉那个邮箱，然而这么久了 Xray 已经被 fork 了 N 份，到处都有备份，删不完的，光是这个 PR 就有 https://github.com/XTLS/Xray-core/commit/8da3d3e78a0da7b0388acceb5ef8892e6d3d4a6f.patch

**Pull request merged**
