### PR TITLE
Add browser dialer for splithttp

### PR DESCRIPTION
**Pull request by mmmray**
this is a bit buggy, the download is interrupted 50% of the time

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks! I will take a look later. Main has been updated to use new logger:
- errors.LogInfo(ctx, msg...)
- errors.LogInfoInner(ctx, err, msg...)

**Comment by yuhan6665** [comment]
Although I don't know much about the browser dialer, I looked over the commits, I think it is good and we can merge and keep improving in main.

**Comment by yuhan6665** [comment]
I will merge later if no other comments..

**Comment by RPRX** [comment]
主要是怕把原有的 WSS Browser Dialer 改炸，不过这功能用起来麻烦些所以用的人不多，毕竟目前 GFW 没封 uTLS，uTLS 更方便

所以虽然我没深入看代码，但我觉得可以先合了，~~然后等喜欢折腾的用户当小白鼠~~

**Pull request merged**
