### PR TITLE
Add NB4A in README/Other/sing-box

### PR DESCRIPTION
**Pull request by Vincent-SOE**
[NB4A](https://github.com/MatsuriDayo/NekoBoxForAndroid) is an Android client powered by sing-box, which support VLESS, REALITY and many other xray features.

License: [GPLv3](https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/main/LICENSE)

### CODE REVIEW

**Comment by nekohasekai** [comment]
I'm afraid Xray is not an advertising board for all applications that support its protocol, why do you need to write these things in the README instead of in the documentation like V2Ray?

**Comment by nekohasekai** [comment]
I think you should remove everything that is not an Xray client or not open source

**Comment by RPRX** [comment]
@chika0801

**Comment by RPRX** [comment]
[当初我就说了把其它内核的相关项目列进来怪怪的](https://github.com/XTLS/Xray-core/pull/1796#issuecomment-1471985542)，[不过既然被手快合了](https://github.com/XTLS/Xray-core/pull/1796#issuecomment-1482317473)，我再给删了会显得不妥，但是如果其它内核的作者希望删掉相关内容，那么当然应该删掉，不应强求

Xray-core 的 README 是一份简单的 guidance，列出 Xray-core 相关的项目是很正常的，包括如何安装、配置示例、图形客户端、替代选择等，正如 GitHub 上的其它很多项目一样。这些内容放在哪只是不同项目的偏好而已，不存在对错之分，个人觉得放 README 更直观，~~况且最开始没有文档~~。至于是否允许 non-free，MPL 并没有那么强的传染性，这就是本项目的价值取舍。

**Pull request closed without merging**
