### PR TITLE
feat: ctx initialization for core.(functions)

### PR DESCRIPTION
**Pull request by rurirei**
as for v2fly/v2ray-core#698 

ctx initialization for `core.Dial()` requires this as method `core.RequireFeatures()` introduced in dispatcher.newFakeDNSSniffer().

### CODE REVIEW

**Comment by rurirei** [comment]
@rprx hopes apply as soon.

**Comment by rurirei** [comment]
c.c. @JimhHan @AkinoKaede

**Comment by rurirei** [comment]
😪  i'm waiting for somemore PRs to be reviewed to make a new release ::(

**Comment by AkinoKaede** [comment]
> 😪 i'm waiting for somemore PRs to be reviewed to make a new release ::(

Sorry, i am too busy to review it.

**Comment by rprx** [comment]
> 
> 
> 😪 i'm waiting for somemore PRs to be reviewed to make a new release ::(

需要花些时间来评估，可以先本地 merge，无需等这边

**Pull request closed without merging**
