### PR TITLE
update: release.yml

### PR DESCRIPTION
**Pull request by thank243**
Replace old download URL.
This is an elegant implemention, Please re PR it and squash prev version.

### CODE REVIEW

**Comment by yuhan6665** [comment]
Looks good to me.

**Comment by thank243** [comment]
Hi @yuhan6665 , If it is possible to implement a RemoveFeature method to hotload the features in the core?

**Comment by yuhan6665** [comment]
I think possible although we are currently lacking devs ;)
You can open a new issue and present your idea details. For example, what feature you want to change?

**Comment by thank243** [comment]
I want to hot reload dns feature and when remove user the connection should be closed at the same time.

**Pull request merged**
