### PR TITLE
Add InvisibleMan-XRay GUI client

### PR DESCRIPTION
**Pull request by InvisibleManVPN**
This is a simple and easy-to-use GUI client based on xray-core for windows platform.

### CODE REVIEW

**Comment by InvisibleManVPN** [comment]
@RPRX I developed this GUI client for users that just want to connect with xray. There is no additional feature and has a simple UI. It's easy to use and supports importing configs from the file and also supports vmess, vless, trojan, and shadowsocks config links. If you have any suggestions, I'll be happy to talk about them.

Thanks

**Comment by yuhan6665** [comment]
@InvisibleManVPN thanks for your contribution! Can you rebase on top of main?

**Comment by RPRX** [comment]
有两个小细节，一是正确拼写为 Xray（lower case r），~~二是其实我们不太喜欢名字中带 VPN 的~~

不过问题不大，我觉得这个项目可以加入 README，今天我会调整下它，顺便加入这个项目

**Comment by InvisibleManVPN** [comment]
@yuhan6665 Thanks for your response. Sure, I rebase it.
@RPRX Also, I can fix the name `InvisibleMan-XRay` to `InvisibleMan-Xray` in the README file.

**Comment by RPRX** [comment]
Added.

**Pull request closed without merging**
