### PR TITLE
Refactor: new Shadowsocks validator

### PR DESCRIPTION
**Pull request by AkinoKaede**
I think #625 may be fix by this PR.

### CODE REVIEW

**Comment by gfw-report** [comment]
Hi @AkinoKaede,

Thank you for spending efforts trying to fix this problem.

Our testing shows that the problem has not been fixed completely as of this commit `6d87f9cfa9218df02f8057af27de083bc15243c1`. Below is how we tested it and you can try to reproduce it yourself:

Open the first terminal to build and run Xray. The `config.json` is the same as in https://github.com/XTLS/Xray-core/issues/625#issue-932218787:

```sh
git clone https://github.com/AkinoKaede/Xray-core.git -b refactor-shadowsocks-validator
go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main
./xray < config.json
```

Open the second terminal to quickly run testings. And you can see:

The server will wait indefinitely when receiving 1 byte of invalid data:

```sh
python3 -c "print('a' * 1)" | nc -v localhost 12345
```

The server will, with some probabilities, either 1) close the connection immediately; or 2) wait indefinitely:

```sh
for i in {1..10}; do python3 -c "print('a' * 500)" | nc -v localhost 12345; done 
```

Looking forward to your patches.

**Comment by rprx** [comment]
“读取超时 -> drain with 随机超时”机制应该可以解决上述问题

**Comment by maker2002** [comment]
@AkinoKaede 关于““读取超时 -> drain with 随机超时”机制”可以在你的代码中更新一下吗？感谢感谢！

**Comment by AkinoKaede** [comment]
> @AkinoKaede 关于““读取超时 -> drain with 随机超时”机制”可以在你的代码中更新一下吗？感谢感谢！

抱歉，我没有什么精力和兴趣完成这项工作。BTW，在遭到某些自以为在维护社区的人的勒索后，我觉得我没有必要继续做此类工作。

**Comment by Butterflyflower** [comment]
@AkinoKaede

**Comment by maker2002** [comment]
> 
> 
> > @AkinoKaede 关于““读取超时 -> drain with 随机超时”机制”可以在你的代码中更新一下吗？感谢感谢！
> 
> 抱歉，我没有什么精力和兴趣完成这项工作。BTW，在遭到某些自以为在维护社区的人的勒索后，我觉得我没有必要继续做此类工作。

很遗憾听到这个消息。不知 @RPRX 未来有空完成这个机制吗？

**Comment by maker2002** [comment]
> 
> 
> > @AkinoKaede 关于““读取超时 -> drain with 随机超时”机制”可以在你的代码中更新一下吗？感谢感谢！
> 
> 抱歉，我没有什么精力和兴趣完成这项工作。BTW，在遭到某些自以为在维护社区的人的勒索后，我觉得我没有必要继续做此类工作。

目前使用1.4.2版的xray，shadowsocks，chacha20加密，无混淆，无插件，每日流量3G左右，最近几天每天都被封一个端口；能否请@AkinoKaede再考虑下更新下代码？我可以付费资助。

**Comment by AkinoKaede** [comment]
For the first problem that GFW Report reported, Xray need to read 50 bytes to authenticate the users, it is caused by the multi-user feature, and I don't have a good idea to resolve it.
For the second problem, Xray will wait indefinitely until read a random size if the connection is invalid. It was design to avoid probing weakness, and it called `Drain`. The seed of random size is decided by the users' key and cipher or the timestamp when server received the first connection.

**Comment by AkinoKaede** [comment]
Since there was no maintainer reviewing this Pull Request or commenting on it for a long time, I closed it.

**Comment by AkinoKaede** [comment]
I reopened it. And try to resolve the conflicts. I don't have enough time to work, so please review it as soon as possible.

**Comment by FranzKafkaYu** [comment]
> time

附议

**Comment by yuhan6665** [comment]
感谢大佬 测试了似乎可以解决主动探测的问题

**Comment by moranno** [comment]
复议，感谢大佬！！！

**Comment by FranzKafkaYu** [comment]
Well done!Thanks for your hard work! @AkinoKaede @gfw-report @yuhan6665

**Comment by AkinoKaede** [comment]
Oh, sorry. I found a bug that the header is shorter than 50 bytes in none cipher.

**Comment by AkinoKaede** [comment]
> Oh, sorry. I found a bug that the header is shorter than 50 bytes in none cipher.

Some protocols like SMTP will not work with none cipher.

**Pull request merged**
