### PR TITLE
DialerProxy: Fix SplitHTTP H3 dialerProxy

### PR DESCRIPTION
**Pull request by mmmray**
I implemented the suggestions in #3560, but I ran into some difficulties:

* quic-go spews a bunch of warnings when net.UDPConn is not passed -- how to turn those off? https://github.com/quic-go/quic-go/blob/c40d4ccb7fe00974095f06a7eb5ac00dd62b7f5b/sys_conn_buffers_write.go#L19
* implementing PacketConn on cnc/connection still does not appear to work
* a panic was predicted because of constant LocalAddr, but I can't actually reproduce it. Instead, all requests encounter an EOF error. In WireShark I see some packets being sent to the server, and no response

### CODE REVIEW

**Comment by RPRX** [comment]
SplitHTTP H3 不支持 dialerProxy 只是我不小心发现的，实际上似乎没有这样的使用场景，有时间可以先实现 https://github.com/XTLS/Xray-core/issues/3560#issuecomment-2241990893

**Comment by ahmad0489** [comment]
It is true that the dialer doesn't work with splithttp h3, but there is another way to send splithttp h3 outbound to another outbound. 
Here, I have considered freedom (direct) as the second outbound for simplicity, but I also tested it with vless and vmess and it was connected.
``` json
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "quic",
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
{
      "listen": "127.0.0.1",
      "port": 23451,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "ip or domain", // config domain or ip
            "port": 443,  // config port
         "network": "tcp,udp",  // udp is required
         "timeout": 0,
        "userLevel": 8,
        "followRedirect": false
      },
      "tag": "proxytodirect"
    }
  ],
  "log": {
    "loglevel": "none"
  },
  "outbounds": [
  {
      "mux": {
        "concurrency": 8,
        "enabled": false,
        "xudpConcurrency": 8,
        "xudpProxyUDP443": "allow"
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "127.0.0.1",
            "port": 23451,
            "users": [
              {
                "encryption": "none",
                "flow": "",
                "id": "your-id", // config id
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "splithttp",
        "security": "tls",
        "splithttpSettings": {
          "host": "your.host",  // config host
          "path": "/yourpath"  // config path
        },
        "tlsSettings": {
          "allowInsecure": false,
          "alpn": [
            "h3" // quic
          ],
          "fingerprint": "chrome",
          "serverName": "your.sni" // config sni
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
   // rule to send dokodemo-door to direct.
{
        "inboundTag": [
          "proxytodirect"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
    // It is important to set DNS and send it to the right outbound (i.e. the second outbound) if you put the domain in the address section of dokodemo-door.
      {
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

` A few important points: `

1- If the second outbound has Mux, it must be xudpProxyUDP443 allow or skip.

2- Pay attention to dns, I explained it in the form of a comment in the code.

` I used this method before to send warp (wireguard) to vless, and now I tested it with splithttp h3 and it connected without any problem. `

**Comment by ahmad0489** [comment]
> > It is true that the dialer doesn't work with splithttp h3, but there is another way to send splithttp h3 outbound to another outbound.
> 
> The discussion is about how to fix it rather than using another way to workaround it. The dialer does work, and dialerProxy will work after applying the changes I mentioned. It is dialer reuse(?) that causes a very basic configuration (without dialerProxy) having connection issues.

Pay attention to the first paragraph of my comment. I didn't say don't improve dialerproxy! 
I temporarily taught a method for those who need it. 
As I said: I used this method before to send warp (wireguard) to vless, and now I tested it with splithttp h3 and it connected without any problem.

Pay attention to what is written on the xray github page.
https://github.com/XTLS/Xray-core/releases/tag/v1.8.23
` 下个版本主要会引入 multiplex control，以及支持 H3 dialerProxy。目前我们计划等到 uQuic v0.1.0 时用其替换 quic-go。`

**Comment by yuhan6665** [comment]
Looks good to me, thanks all!
@dyhkwong consider raise a separate ticket for your issue to get to the bottom of it

**Pull request merged**
