### PR TITLE
XHTTP client: Refactor "packet-up" mode, chasing "stream-up"

### PR DESCRIPTION
**Pull request by RPRX**
[XHTTP](https://github.com/XTLS/Xray-core/discussions/4113) packet-up 模式的上行发送大量数据会出问题，此前 https://github.com/XTLS/Xray-core/issues/3972#issuecomment-2480945983 只修好了一部分，这个 PR 基于 https://github.com/XTLS/Xray-core/issues/4100#issuecomment-2533408988 “**back pressure 没到位 ...... 本来就应该等上个 POST 把数据写进系统网络栈后再弄下一个 POST**”，应该是彻底修好了

比如操作系统 TCP 栈还积压着大量数据没发完，此时你又想给它塞数据，操作系统为了让你缓缓就会迟点再返回，这就是 back pressure，很好理解。而 packet-up 模式以前为了不等 response 就发下一个 POST，多个本应串行的 POST 其实是并行发出的，且并发数达到默认值 100 前无视 back pressure，这两点加起来导致了疑难杂症，比如某个 POST 迟迟没能发完，就堵塞了。

- **这个 PR 通过 traceWroteRequest 确保了发完上一个 POST 的 body 再发下一个，且有来自操作系统的天然 back pressure**
- **其实这两点加起来差不多就是流式上行了，理论上和 stream-up 的表现不会有太大差距**

H3 的 httptrace 尚未合并 https://github.com/quic-go/quic-go/pull/4749 ，且 Xray 的依赖暂时锁在 v0.46.0，所以我 fork 了：https://github.com/XTLS/quic-go/commit/571fae25a5baf4a9e49ab71f4e1727025fa486c9 ，顺便把 traceGotConn 也加上了，**此外 `scMaxConcurrentPosts` 改成了 `scMaxBufferedPosts`，仅服务端，默认值 30**

最后当然是：

- **ETH/USDT/USDC: `0xDc3Fe44F0f25D13CACb1C4896CD0D321df3146Ee`**
- **Project X NFT: https://github.com/XTLS/Xray-core/discussions/3633**
- **REALITY NFT: https://github.com/XTLS/Xray-core/discussions/4113**

### CODE REVIEW

**Comment by RPRX** [comment]
Waiting for https://github.com/quic-go/quic-go/pull/4749

不过我看了下它这个咋是 str.SendRequestHeader(req) 后也调用 WroteRequest()：https://github.com/quic-go/quic-go/pull/4749/files#diff-af46d577ef879fcda162f4cf1688ef52a40c21fd08df2d083802d5b0306238d1

~~我再看看 Go 官方 HTTP 库~~

**Comment by RPRX** [comment]
我看了下 Go 的 H2 代码，行为是符合直觉的，https://github.com/quic-go/quic-go/pull/4749 应该是写错了

**Comment by RPRX** [comment]
~~又仔细看了下，人家没写错，是 err 不为 nil 的情况~~

**Comment by RPRX** [comment]
~~那我重来~~，Waiting for https://github.com/quic-go/quic-go/pull/4749

**Comment by dragonbreath2000** [comment]
tried this now , with setting  scMaxEachPostBytes to 100000,the upload did not stuck like before with my crappy isp,great work,thanks

**Comment by RPRX** [comment]
> tried this now , with setting scMaxEachPostBytes to 100000,the upload did not stuck like before with my crappy isp,great work,thanks

1000000 呢

**Comment by dragonbreath2000** [comment]
> 1000000

when i set it to 1000000,it does a big burst at first but speed goes down after that a lot,my upload is extremly limited with my current isp,lowering postBytes seems to improves it for me

**Comment by RPRX** [comment]
> > 1000000
> 
> when i set it to 1000000,it does a big burst at first but speed goes down after that a lot,my upload is extremly limited with my current isp,lowering postBytes seems to improves it for me

没有 stuck 就是好事，试试仅把 `scMinPostsIntervalMs` 设为 100，今天的版本大概会先这么改（不会带上这个 PR）

**Comment by RPRX** [comment]
> 不会带上这个 PR

由于 H3 尚未支持 trace，只能依赖于 `defer wroteRequest.Close()`，延迟太高了，对了 @dragonbreath2000 你测的是 H2 吧

**Comment by dragonbreath2000** [comment]
> @dragonbreath2000You are measuring H2, right?

Yes

**Comment by RPRX** [comment]
貌似这个 PR 之后客户端就不需要 `scMaxConcurrentPosts` 了，完全依赖系统网络栈的 back pressure 就行

**Comment by RPRX** [comment]
干脆一步到位，于是我 fork 了 quic-go v0.46.0，加了两个 tracepoint：https://github.com/XTLS/quic-go/commit/571fae25a5baf4a9e49ab71f4e1727025fa486c9

**Comment by RPRX** [comment]
干脆一步到位，于是我 fork 了 quic-go v0.46.0，加了 Xray 用到的两个 tracepoint：https://github.com/XTLS/quic-go/commit/571fae25a5baf4a9e49ab71f4e1727025fa486c9

**Comment by RPRX** [comment]
To XQZR：但凡你点开看下这个 commit https://github.com/XTLS/quic-go/commit/571fae25a5baf4a9e49ab71f4e1727025fa486c9 ，它就是从 quic-go PR 复制来的，上游合并后直接升级就行

**Comment by RPRX** [comment]
To 风扇滑翔翼：就是 POST 的 body 全被系统网络栈收了后再弄下一个，这样能保证顺序且自然有 back pressure，类似于 stream

**Comment by RPRX** [comment]
> https://github.com/refraction-networking/uquic

它似乎还没有准备好

**Comment by RPRX** [comment]
~~其实不用更新文档了，我写那篇文章就是为了把文档整个替换掉~~

**Comment by Smallthing** [comment]
是不是只有日志才能观察出握手的是H2还是H3？是3模式里面的哪一个？

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/commit/7463561856f75ed42564e8a6fad722c6bafc74a6 日志加了 HTTP 版本和 host，上下行分离的下行也有日志了

**Comment by mehdifirefox** [comment]
Thank you very much for the hard work.

I haven't followed the news and information for a long time.
I don't know what progress has xray

I use more free servers
I wanted to see if I update it is good?
No need to do anything else to get better?

**Pull request merged**
