### PR TITLE
Fix SplitHTTP race condition when creating new sessions

### PR DESCRIPTION
**Pull request by yuhan6665**
It seems SH can't receive a short message too fast

### CODE REVIEW

**Comment by yuhan6665** [comment]
@mmmray I made some progress. I think it is a unit test only issue that is unlikely in real use.
I see a race condition between server read
https://github.com/XTLS/Xray-core/blob/558cfcc5072f438b735b6e4bfd88f20ca6093f95/transport/internet/splithttp/upload_queue.go#L57
and client push packet to the channel
https://github.com/XTLS/Xray-core/blob/558cfcc5072f438b735b6e4bfd88f20ca6093f95/transport/internet/splithttp/upload_queue.go#L41
It seems server read must happen before client push. But can't understand why the other way would hang..

**Comment by RPRX** [comment]
先不要给 main push 新的 commit，等待 https://github.com/XTLS/Xray-core/pull/3530

**Comment by yuhan6665** [comment]
> @yuhan6665 yeah I don't understand it either. there is a test that writes before read: https://github.com/XTLS/Xray-core/blob/13c2d5071c5e1e6789635d5f205e685ae92ece08/transport/internet/splithttp/upload_queue_test.go
> 
> is this hanging test locally reproducible?

I removed the 5 seconds delay and was running the test for 100 times -count 100

**Comment by RPRX** [comment]
> I think it is a unit test only issue that is unlikely in real use.

~~听起来新版不必等这个 PR~~

**Comment by yuhan6665** [comment]
@mmmray maybe it is different environment but I tried two fixes you mentioned, it still hangs occasionally here
`/usr/local/go/bin/go test -timeout 30s -run ^Test_listenSHAndDial$ github.com/xtls/xray-core/transport/internet/splithttp -count 100`

**Comment by vrnobody** [comment]
我发现两个问题：

第一，upsertSession()有小概率为同一个sessionId生成多个uploadQueue，所以应该给它加个锁
https://github.com/XTLS/Xray-core/blob/9e6d7a3cb0c5d60b8ef3cedef7ffaf610547f619/transport/internet/splithttp/hub.go#L58

第二，unit test里面不能有time.Sleep()之类的函数，所以要注释掉下面这行。
https://github.com/XTLS/Xray-core/blob/9e6d7a3cb0c5d60b8ef3cedef7ffaf610547f619/transport/internet/splithttp/splithttp_test.go#L66

修改后的代码： https://github.com/vrnobody/xraycore/commit/1ee424f304c306a147ebfece465cdb52bdaa8815
  

关于第二点，我也不知道为什么，但下面这个unit test有可能失败。非常奇怪。
`go test -run ^Test_Time_Sleep$ -count=100 -timeout=30s ./transport/internet/splithttp/splithttp_test.go`
```go
func Test_Time_Sleep(t *testing.T) {
	start := time.Now()
	fmt.Println("sleeping...")
	time.Sleep(5 * time.Second)
	dur := time.Since(start).Milliseconds()
	fmt.Println("wakeup after", dur, "ms")
}
```

**Comment by RPRX** [comment]
~~听起来新版可以等这个 PR~~

**Comment by RPRX** [comment]
我觉得无论 tests 修好没，至少 SplitHTTP 都需要这个 fix，所以先合了，credit 给你们三位，感谢！

**Comment by yuhan6665** [comment]
测试无问题 感谢 @vrnobody！

**Pull request merged**
