### PR TITLE
Old soldiers never die

### PR DESCRIPTION
**Pull request by yuhan6665**

### CODE REVIEW

**Comment by cross-hello** [comment]
From Jul 28, 2020  to Mar 2, 2023

Rest in peace

Mar 2, 2023 12:01:39 yuhan6665 ***@***.***>:

> ----------------------------------------
> 
> *You can view, comment on, or merge this pull request online at:*
> 
>   https://github.com/XTLS/Xray-core/pull/1725
> 
> 
> *Commit Summary*
> 
* > 8d2ab53[https://github.com/XTLS/Xray-core/pull/1725/commits/8d2ab532d5fc322ed1e927177bfe59cb03caccca] Old soldiers never die
> 
> *File Changes*
> 
> (34 files[https://github.com/XTLS/Xray-core/pull/1725/files])
> 
* > *M* go.mod[https://github.com/XTLS/Xray-core/pull/1725/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6] (1)
* > *M* go.sum[https://github.com/XTLS/Xray-core/pull/1725/files#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63] (2)
* > *M* infra/conf/transport_internet.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-f898f86523782721aa861d5d5f610608420ae29acf3a27eb71fa618590179d19] (135)
* > *M* infra/conf/trojan.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-dc97d84858de269d395e45fc80ac55399589023335378b3db8ec2d3ba08d3b9e] (10)
* > *M* infra/conf/vless.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-d26f7b46a9f3b7d26058c845aa7e322e1ae15207400c91fd86137124ce145b2c] (10)
* > *M* infra/conf/vless_test.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-43cd544696c806819b9b96ed4c315e8056fea36dfb8c04b457a90a367fea9812] (8)
* > *M* infra/conf/xray.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-2683dbaba14bc856bb5c6f6e664313d25dd246b4e262deb3e886579b4f48a3b4] (17)
* > *M* main/distro/all/all.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-1e3a15d67ee219b84581d48fe3a9865048b2aa88f88cac0faf3a00a006a9f24c] (1)
* > *M* proxy/trojan/client.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-6277c779e50b2cd2ff634fd03ada75ec0f19d320aa813667baeb4635dca79745] (61)
* > *M* proxy/trojan/protocol.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-12e5a0950a625d40367696d3c8078461d3bf2aa807ce87d6b59cde93c15bc8df] (93)
* > *M* proxy/trojan/server.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-5ff3b485cfa00582ff13547ff84c7864abb7ffb06aaa6fb418ecadb3f8c7ba42] (67)
* > *M* proxy/vless/account.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-fc6d1d45758308af13b2e36c1f9ed4a01cbfc101ee5ac4ff706ea1fe1e3b8cda] (2)
* > *M* proxy/vless/account.pb.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-8880e6f33243a48988070d2c1490c5739334d72212c3a1bf0feca4dfce1c3551] (2)
* > *M* proxy/vless/account.proto[https://github.com/XTLS/Xray-core/pull/1725/files#diff-bbb18da0b157cfaa727bbd481bea37e30dafb6c4efffce9b4158e8041e896a0d] (2)
* > *M* proxy/vless/encoding/addons.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-6a1593dd76977a4e8eb6448bd6f40434a5199ca9d1c92406f2bf69b4b01bdcfb] (2)
* > *M* proxy/vless/encoding/encoding.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-1065fe03c2a45a59cacc15cca000080bd9ec4aeba8e7efb410134c8a98a0793e] (61)
* > *M* proxy/vless/inbound/inbound.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-35b30f4c19a774a865d83f273a0a5f8a6925c96d6c3f4e6bbf2aaca850705b62] (95)
* > *M* proxy/vless/outbound/outbound.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-d3f464796a20ae1697d07a6fdb7a6581bcae5ad22571d6c3c19f0052ef29e68a] (93)
* > *M* proxy/vless/vless.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-9798f9a9d8f386e381a6736d672cd9a8c8980652e45106ed01d171525954bed4] (3)
* > *M* transport/internet/domainsocket/dial.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-b6a483c4508e1bb4c079c9009aa5c052c6c94a0aba604cc2b88844cd38a9d32e] (3)
* > *M* transport/internet/domainsocket/listener.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-36851e73c5d7dcff48151264891f43286a50daae0653348d411f9afd11d4350e] (8)
* > *M* transport/internet/kcp/dialer.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-a491ef2a4467b61743ff239fda65b9eee3743b063a8671e99e52d254f0e6a1ea] (3)
* > *M* transport/internet/kcp/listener.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-6e1b7daf482d8d0ad5b5246c295b8963b0519a692420019a90b5a57cae3fd170] (8)
* > *M* transport/internet/tcp/dialer.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-89706c816016142fabd1c97a35ee6e8cb7e779a288abdbb2036b2630edd847f0] (4)
* > *M* transport/internet/tcp/hub.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-4bf6f9bf07ca189c5286884809d4230c573a815113556acc083b362312c83168] (8)
* > *D* transport/internet/xtls/config.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-58484d889dda0c3348771d110e484afa40822070916576509f819b658a478d29] (377)
* > *D* transport/internet/xtls/config.pb.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-479fa40da5ec4811a4ac980359e2995e384b2386ce51e036bc4e0283b457a3dd] (478)
* > *D* transport/internet/xtls/config.proto[https://github.com/XTLS/Xray-core/pull/1725/files#diff-c7dc297158a3324ca230fad65c00e8e3f8adaf72afff9298e35fa912c3f161af] (76)
* > *D* transport/internet/xtls/config_other.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-0afcce6aebf9a241cc7497e1463c6760cfe8b00ab74f74d44bb4290f3ea548c8] (53)
* > *D* transport/internet/xtls/config_test.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-5e7ef0e510898764c23dd7e1fbcd2bafaf7fd5bf82fbd6a63935e5c79d14188b] (97)
* > *D* transport/internet/xtls/config_windows.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-c75f276ba887c1df9b3237026301744ab2e96fd93e47a486ef2ec761412fab52] (14)
* > *D* transport/internet/xtls/errors.generated.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-7bd0f3584656e5ea67d387aa395df66ac0d23178d0ec157144f7229f5ec19aac] (9)
* > *D* transport/internet/xtls/unsafe.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-53fb99ef1e0529813339646e337fd5488e755b008b4eb06cba430a2057d6aeb8] (6)
* > *D* transport/internet/xtls/xtls.go[https://github.com/XTLS/Xray-core/pull/1725/files#diff-bcb2223cefdce82515649cc69b8fdbe784edcbe4dddd48e5ea3c9152c7202fea] (35)
> 
> *Patch Links:*
> 
* > https://github.com/XTLS/Xray-core/pull/1725.patch
* > https://github.com/XTLS/Xray-core/pull/1725.diff

**Comment by Fangliding** [comment]
把旧的xtls移除力
~~与此同时文档的xtls介绍从未动笔~~

**Comment by rurirei** [comment]
em so `removed != dead` right!?

**Comment by yuhan6665** [comment]
> em so `removed != dead` right!?

They simply fade away

**Comment by RPRX** [comment]
Legends never die, they become a part of ~~you~~ VLESS

**Pull request merged**
