### PR TITLE
workflows: align with doc

### PR DESCRIPTION
**Pull request by tritu**

### CODE REVIEW

**Comment by Beginner-Go** [comment]
通过ci 查看 似乎没起到作用？

**Comment by b0a5p** [comment]
> 通过 ci 查看 似乎没起到作用？

请见 https://github.com/XTLS/Xray-core/pull/978#issuecomment-1064796649

**Comment by yuhan6665** [comment]
If I understand correctly even the current config should also work
```
Setup go stable version spec ^1.17.7
Attempting to resolve the latest version from the manifest...
matching ^1.17.7...
Resolved as '1.17.7'
```
Let's wait for the update from action's side. If current config doesn't resolve 1.17.8 I will merge this pr. Thanks!

**Comment by pg6o** [comment]
Yet, just waiting for https://github.com/actions/go-versions/pull/50

**Comment by yuhan6665** [comment]
Everything works good looks like: https://github.com/XTLS/Xray-core/runs/5579494541?check_suite_focus=true
I suggest no more change is needed and we can close this.
Thanks for all your work!

**Comment by tritu** [comment]
Good to know.
Close this PR then.

**Pull request closed without merging**
