### PR TITLE
Add `TCP_MAXSEG`

### PR DESCRIPTION
**Pull request by xqzr**
```json
{
 "streamSettings": {
  "sockopt": {
   "TCPMaxSeg": 1440
  }
 }
}
```

### CODE REVIEW

**Comment by RPRX** [comment]
感谢 PR，相比于只分割 TLS Client Hello，这个方法合理些，~~虽然会影响速度~~

麻烦研究一下 https://github.com/XTLS/Xray-core/pull/1779#issuecomment-1518907605

**Comment by xqzr** [comment]
> 感谢 PR，相比于只分割 TLS Client Hello，这个方法合理些，~虽然会影响速度~
> 
> 麻烦研究一下 [#1779 (comment)](https://github.com/XTLS/Xray-core/pull/1779#issuecomment-1518907605)

要是成了 ~~，还怎么刷 commit 记录😋~~

**Comment by Otisist** [comment]
Hello guys. i adding this in config client side. But I want to know if this works properly and does it fragment?
or this way:
"fragment" : {
     "packets": "tlshello",
     "interval": "10-20",
     "length": "5-30"
  } 

Is there a way to find out?
I tested with Wireshark, even without a proxy, ip.flag_offset was still present in all packets!
I even tested the config and servers that don't have fragments, and this flag was still there
I'm really confused
I would appreciate it if you could guide me or introduce a source that will tell me how to actually do the packet fragment

@RPRX @xqzr

**Comment by xqzr** [comment]
> Hello guys. i adding this in config client side. But I want to know if this works properly and does it fragment? or this way: "fragment" : { "packets": "tlshello", "interval": "10-20", "length": "5-30" }
> 
> Is there a way to find out? I tested with Wireshark, even without a proxy, ip.flag_offset was still present in all packets! I even tested the config and servers that don't have fragments, and this flag was still there I'm really confused I would appreciate it if you could guide me or introduce a source that will tell me how to actually do the packet fragment
> 
> @RPRX @xqzr

这似乎是 应用层 分段，与本 PR 无关

**Comment by Otisist** [comment]
> > Hello guys. i adding this in config client side. But I want to know if this works properly and does it fragment? or this way: "fragment" : { "packets": "tlshello", "interval": "10-20", "length": "5-30" }
> > Is there a way to find out? I tested with Wireshark, even without a proxy, ip.flag_offset was still present in all packets! I even tested the config and servers that don't have fragments, and this flag was still there I'm really confused I would appreciate it if you could guide me or introduce a source that will tell me how to actually do the packet fragment
> > @RPRX @xqzr
> 
> 这似乎是 应用层 分段，与本 PR 无关


So, if we combine this with "tlshello" fragmenting, I guess GFW can be bypassed for upload speed. Because it seems that after a few minutes of uploading, the speed decreases drastically. Even with clean SNI.

**Comment by xqzr** [comment]
> > > Hello guys. i adding this in config client side. But I want to know if this works properly and does it fragment? or this way: "fragment" : { "packets": "tlshello", "interval": "10-20", "length": "5-30" }
> > > Is there a way to find out? I tested with Wireshark, even without a proxy, ip.flag_offset was still present in all packets! I even tested the config and servers that don't have fragments, and this flag was still there I'm really confused I would appreciate it if you could guide me or introduce a source that will tell me how to actually do the packet fragment
> > > @RPRX @xqzr
> > 
> > 
> > 这似乎是 应用层 分段，与本 PR 无关
> 
> So, if we combine this with "tlshello" fragmenting, I guess GFW can be bypassed for upload speed. Because it seems that after a few minutes of uploading, the speed decreases drastically. Even with clean SNI.

这可能取决于你的 ISP

**Pull request merged**
