### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hiddify1**
Adding Hiddify Clients for windows and android that are a fork of V2RayN and V2RayNG with more features and adding auto server selector

### CODE REVIEW

**Comment by RPRX** [comment]
可以合并。我记得 N 代表 Windows，NG 代表 Android，所以 HiddifyAndroidNG 这样的命名有点怪，你看下需不需要改成 HiddifyNG。仅建议，当然如果你觉得没问题也行。

**Comment by chika0801** [comment]
安装了 HiddifyAndroidNG 看了下界面。这老哥在v2rayNG上改了改吧。:smirk:

**Comment by Extreme-Icer** [comment]
> 安装了 HiddifyAndroidNG 看了下界面。这老哥在v2rayNG上改了改吧。😏

是这样，不过界面看起来还算可以

**Comment by hiddify1** [comment]
Thank you for your suggestion. I have made the changes on the repository names

**Comment by tavallaie** [comment]
Due to this issue, I request to revert the change https://github.com/XTLS/Xray-core/issues/2132#issue-1722152791

**Pull request merged**
