### PR TITLE
Replace TCP Segmentation with TLS Hello Fragmentation

### PR DESCRIPTION
**Pull request by rrouzbeh**
Big shout-out to @sambali9 for taking the initiative to add fragmentation to the freedom project - nice one! I took a closer look, and it seems what we've got is TCP segmentation rather than fragmentation. The thing is, this doesn't quite work in Iran because of GFW's TCP reassembly capabilities. So, I've gone ahead and made some changes to shift from TCP segmentation to TLS Hello fragmentation.

Here's a sample configuration you can use for testing the new implementation:
```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": "1083",
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": "0.0.0.0"
      }
    },
    {
      "listen": "0.0.0.0",
      "port": "1081",
      "protocol": "http"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "fragment": {
          "length": "100-200",
          "interval": "1-2",
          "packets": "1-3"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true
        }
      }
    }
  ]
}

```

### CODE REVIEW

**Comment by rrouzbeh** [comment]
**TCP Segmentation:**
Screen Shot 2023-05-23 at 1 42 20 AM

**TLS Hello Fragmentation:**
Screen Shot 2023-05-23 at 1 38 13 AM

**Comment by RPRX** [comment]
感谢 PR，其实当初我看到你改的代码时就有疑惑，因为一些 TLS 服务端实现是无法正确处理这种情况的，这个实测兼容性如何？

以及我想了解一下，https://github.com/GFW-knocker/gfw_resist_tls_proxy 这个项目是哪种方式？两种方式对比效果如何？

**Comment by mortada-jafar** [comment]
Is it working for you? I tested your changes, but the upload speed is throttled.






```
{
  "log": {
    "loglevel": "warning"
},

"inbounds": [
  {
    "listen": "0.0.0.0",
    "port": "1083",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "0.0.0.0"
    }
  },
  {
    "listen": "0.0.0.0",
    "port": "1081",
    "protocol": "http"
  }
],
    "outbounds": [
        {
        "protocol": "vmess",
        "settings": {
          "vnext": [
            {
              "address": "104.21.20.148", //cloudflare dirty ip
              "port": 443,
              "users": [
                {
                  "alterId": 0,
                  "encryption": "",
                  "flow": "",
                  "id": "mortada3",
                  "level": 8,
                  "security": "auto"
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "ws",
          "security": "tls",
          "tcpSettings": {
            "header": {
              "type": "none"
            }
          },
          "tlsSettings": {
            "allowInsecure": false,
            "fingerprint": "",
            "publicKey": "",
            "serverName": "server_domain",
            "shortId": "",
            "show": false,
            "spiderX": ""
          },
          "wsSettings": {
            "headers": {
              "Host": "server_domain"
            },
            "path": "/"
          },
          "sockopt": {
            "dialerProxy": "freedom"
          }
        },
        "tag": "proxy"
      },      
      {
        "protocol": "freedom",
        "settings": {
          "fragment": {
            "length": "50-100",
            "interval": "50-100",
            "packets": "1-3"
          }
        },
        "streamSettings": {
          "sockopt": {
            "tcpNoDelay": true
          }
        }
      }
    ]
  }

```

**Comment by rrouzbeh** [comment]
> [RPRX](/RPRX)

@RPRX 
Thanks for your note! I ran the code on my network and it worked with most apps and sites - except bing.com. There was a tls handshake issue there, but I'm looking into it. Though it worked in my tests, I'd say give it a try in other environments too just to double-check its compatibility.

**Comment by mortada-jafar** [comment]
I tested the config with MCI 
Can you confirm that is working with MCI?

**Comment by A5DkjGQUZx** [comment]
> > [RPRX](/RPRX)
> 
> @RPRX Thanks for your note! I ran the code on my network and it worked with most apps and sites - except bing.com. There was a tls handshake issue there, but I'm looking into it. Though it worked in my tests, I'd say give it a try in other environments too just to double-check its compatibility.

@rrouzbeh any updates on your findings and investigations?

**Comment by rrouzbeh** [comment]
@A5DkjGQUZx
Unfortunately, I'm unable to test on the MCI network, but as you can see, it has worked well with two Iranian service providers.
If someone else could evaluate it and provide feedback, that would be wonderful.

And @mortada-jafar, we can connect if you're able to verify it on your network and help us discover a solution.
My email address is my GitHub username @gmail.

**Comment by RPRX** [comment]
可以加一个写法以和原有的模式区分，这种分片仅针对 TLS Client Hello，可以 `"packets": "tlshello"`，它与填 `"1"` 的含义不同

**Comment by RPRX** [comment]
其实 REALITY 服务端也需要改成支持这种分片，默认开启，反正目标服务端不支持的话就不会正常返回 Server Hello，直接转发

**Comment by X-Oracle** [comment]
I think moving it to TlsObject or RealityObject would be better . since both of them are tls based then fragmentation will work for all traffic using Tls based config.

> https://github.com/XTLS/Xray-core/pull/2131#issuecomment-1559112346

 wouldn't it use more CPU and reduce performance when proxy chaining?

**Comment by X-Oracle** [comment]
> https://github.com/XTLS/Xray-core/pull/2131#issuecomment-1559112346

I have a question regarding how you chained them.

is there a performance deference  between using bellow configs?

```json
"proxySettings": {
        "tag": "fragment"
      }
```

```json
"streamSettings": {
     "sockopt": {
        "dialerProxy": "fragment"
      }
 }
```

**Comment by A5DkjGQUZx** [comment]
> I think moving it to TlsObject or RealityObject would be better . since both of them are tls based then fragmentation will work for all traffic using Tls based config.
> 
> > [#2131 (comment)](https://github.com/XTLS/Xray-core/pull/2131#issuecomment-1559112346)
> 
> wouldn't it use more CPU and reduce performance when proxy chaining?

There have been situations in which a blocked/filtered URL/SNI could be accessed just by fragmenting TLS Hello. Could be added as an option to TLS object but also is useful on bare mode as well.

**Comment by lonerouge** [comment]
> 其实 REALITY 服务端也需要改成支持这种分片，默认开启，反正目标服务端不支持的话就不会正常返回 Server Hello，直接转发

-... . ... - ....... ..- ... . ....... -.-. .- ... . ....... --- ..-. ....... - .... .. ... ....... .- .--. .--. .-. --- .- -.-. .... ....... .. ... ....... --- -. .-.. -.-- ....... - .... .- - ....... ... -. .. ....... -... .-.. --- -.-. -.- .. -. --. ....... .... . ....... -- . -. - .. --- -. . -.. -.--. -.. .- - .- -... .- ... . ....... .. ... ....... ...- . .-. -.-- ....... -... .. -. --. ....... .- -. -.. ....... - .... . .. .-. ....... .--. .-. --- -.-. . ... ... .. -. --. ....... .--. --- .-- . .-. ....... .. ... ....... -- .- ... ... .. ...- . -.--.- ....... .- -. -.. ....... - .... . ....... --- -. .-.. -.-- ....... - .... .. -. --. ....... .-- . ....... -.-. .- -. ....... ... . . ....... ..-. .-. --- -- ....... .. -. -... --- ..- -. -.. ....... ..-. .. .-.. - . .-. .. -. --. ....... .- -. -.. ....... ... . -.-. ..- .-. .. - -.-- ....... .-.. .- -.-- . .-. ....... --- ..-. ....... - .... .- - ....... -.-. ..-. -....- --- -. . ....... ..-. .. .-. . .-- .- .-.. .-.. ....... - .... . -.-- ....... .- .-. . ....... ..- ... .. -. --. ....... - .... . ... . ....... -.. .- -.-- ... ....... .. ... ....... ... -. .. ....... -... .-.. --- -.-. -.- .. -. --. --..-- ....... - .... . ....... --- - .... . .-. ....... - .... .. -. --. ....... .. ... ....... - .... . ....... -. . - .-- --- .-. -.- ....... .-.. .- -.-- . .-. ....... .- -. -.. ....... -- .- --. .. -.-. ....... - .-. .- -. ... .. - ....... --- ..-. ....... -.-. ..-. ....... --- -. . ....... ..-. .. .-. . .-- .- .-.. .-.. ....... .-- .... .. -.-. .... ....... .. ... ....... .. .--. ....... -... .- ... . -.. ....... .-. ..- .-.. . ... ....... .-- .... .. -.-. .... ....... -.-. .- -. ....... -. --- - ....... -... . ....... .--. .-. . ...- . -. - ....... .-- .. - .... ....... .--- ..- ... - ....... .--. .-. --- - --- -.-. --- .-.. ... ....... --- .-. ....... .- -. -.-- - .... .. -. --. ....... . .-.. ... . .-.-.- ....... .--- ..- ... - ....... ... . . ....... - .... .. ... ....... .-. . --. .. --- -. ....... .- ... ....... .-- .- .-. -. .. -. --. ....... ..-. --- .-. ....... -.-- --- ..- .-. ....... .-. . --. .. --- -. --..-- ....... --- ..- .-. ....... -- --- -... .. .-.. . ....... .--. .-. --- ...- .. -.. . .-. ....... .. .--. ... ....... -... . -.-. .- -- . ....... ... - .-. .- -. --. . ....... .- -. -.. ....... .. - ... ....... .- ... -. ....... .. ... -.--. -.. --- -.. ....... --- ..-. ....... .- -- . .-. .. -.-. .- -.--.- ....... .-- .... .. -.-. .... ....... .. ... ....... -. --- - ....... .- ....... --. --- --- -.. ....... ... .. --. -. .-.-.- ....... ... --- ....... -- --- ...- . ....... -.-- --- ..- .-. ....... ..-. ..- -.-. -.- .. -. --. ....... .- ... ... ....... .--- ..- ... - ....... .-. . .-.. . .- ... . ....... - .... .- - ....... - .-.. ... ....... ..-. .-. .- --. -- . -. - .- - .. --- -. ....... .- -. -.. ....... -.. --- -. - ....... -... ..- -.-- ....... - .. -- . ....... ..-. --- .-. ....... - .... . -- .-.-.-

**Comment by RPRX** [comment]
@lonerouge 消息删得挺快，关于 REALITY 你也理解错了，其实我并不关心与该方式配合，我只关心来自中间人的攻击，~~懂的都懂~~

**Comment by RPRX** [comment]
To Ckdnd：我和 @yuhan6665 的备忘录里有十件事，做一些发 v1.8.2，剩下的发 v1.8.3，其中不包括 XTLS 的 0-RTT，近期不会出

**Comment by RPRX** [comment]
我的主要修改：
1. 与已有的 TCP Segmentation 共存，使用 `"packets": "tlshello"` 代表 TLS Hello Fragmentation，比如：
```json
"fragment": {
    "packets": "tlshello",
    "length": "100-200",
    "interval": "10-20" // ms
}
```
2. 原始 PR 的 `length` 固定为 `maxLength`，我把它改为了 `minLength` 到 `maxLength` 随机，符合定义

这方面的代码主要是 @sambali9 和 @rrouzbeh 贡献的，感谢你们的 PR，~~虽然代码有点乱~~，目前我没有时间对它们进行太多美化，只提了些我的想法和建议，并简单改了改关键的部分，以及把他们的代码组合起来，v1.9 再对这些代码进行简化、美化。

**Comment by RPRX** [comment]
目前 XTLS Vision 出站和 REALITY 入站暂不支持分片，不久后会改，但它们支持分片主要不是为了这两个 PR，而是有其它原因。

**Comment by RPRX** [comment]
此外我们需要感谢 @GFW-knocker 的 https://github.com/GFW-knocker/gfw_resist_tls_proxy 项目，但是我必须指出该项目的说法 https://github.com/GFW-knocker/gfw_resist_tls_proxy#can-gfw-block-fragments-skip-if-you-want 并不成立。因为正常的 TLS 都是一次性发完整的 Client Hello，且远小于 MTU，不会有任何形式的分片，所以 GFW 检查第一个包不正常就掐连接即可，无需缓存。

**Comment by A5DkjGQUZx** [comment]
> In addition we need to thank@GFW-knockerhttps://github.com/GFW-knocker/gfw_resist_tls_proxy project, but I have to point out [what](https://github.com/GFW-knocker/gfw_resist_tls_proxy) the project says [https://github.com/GFW-knocker/gfw_resist_tls_proxy#can-gfw-block-fragments-skip-if- you-want](https://github.com/GFW-knocker/gfw_resist_tls_proxy#can-gfw-block-fragments-skip-if-you-want) is not established. Because the normal TLS sends a complete Client Hello at one time, and it is much smaller than the MTU, and there will be no fragmentation in any form, so the GFW checks that the first packet is abnormal and just pinches the connection without caching.

This is indeed true BUT what if in future all standard browsers add a built-in TLS HELLO Fragment support?! Then it would be almost impossible for the GFW to drop all of them. Maybe we can ask for this to be implemented by the Chromium Project!

**Comment by RPRX** [comment]
> This is indeed true BUT what if in future all standard browsers add a built-in TLS HELLO Fragment support?! Then it would be almost impossible for the GFW to drop all of them. Maybe we can ask for this to be implemented by the Chromium Project!

这个想法很有趣，但不具有可行性，因为这些浏览器并不希望增加哪怕一毫秒的延迟，而若没有间隔，分片很容易就能被重组。

**Comment by FranzKafkaYu** [comment]
@RPRX 歪个楼:新版本我们需要一个新的config example😝

**Comment by RPRX** [comment]
> @RPRX 歪个楼:新版本我们需要一个新的config example😝

@yuhan6665 今天会更新文档

最需要注意的是 DNS 出站的行为改了，加上 `"nonIPQuery": "skip"` 才是原来的行为，客户端、服务端的 UI 都需要加一下

**Comment by RPRX** [comment]
`nonIPQuery` 设计成 string 而非 bool，是预留更多的可能性，比如下个版本会加上 geo，还可以试试简单转发，而非先解析再查询

**Comment by moh3nat** [comment]
Can anyone provide a summary explanation of kernel 1.8.2 and added features?

**Comment by Fangliding** [comment]
> 我的主要修改：
> 
> 1. 与已有的 TCP Segmentation 共存，使用 `"packets": "tlshello"` 代表 TLS Hello Fragmentation，比如：
> 
> ```json
> "fragment": {
>     "packets": "tlshello",
>     "length": "100-200",
>     "interval": "10-20" // ms
> }
> ```
> 
> 2. 原始 PR 的 `length` 固定为 `maxLength`，我把它改为了 `minLength` 到 `maxLength` 随机，符合定义
> 
> 这方面的代码主要是 @sambali9 和 @rrouzbeh 贡献的，感谢你们的 PR，~虽然代码有点乱~，目前我没有时间对它们进行太多美化，只提了些我的想法和建议，并简单改了改关键的部分，以及把他们的代码组合起来，v1.9 再对这些代码进行简化、美化。
这部分写了文档吗（）

**Pull request merged**
