### PR TITLE
Implement WireGuard protocol as outbound (client)

### PR DESCRIPTION
**Pull request by nanoda0523**
# Credit
Some of codes are copied from [wireproxy](https://github.com/octeep/wireproxy) and the original license has provided in code.

# Configuration format
~~~jsonc
{
  "protocol": "wireguard",
  "settings": {
    "secretKey": "PRIVATE_KEY",
    // optional, default ["10.0.0.1", "fd59:7153:2388:b5fd:0000:0000:0000:0001"]
    "address": [
      "IPv4_CIDR",
      "IPv6_CIDR",
      "and more..."
    ],
    "peers": [
      {
        "publicKey": "PUBLIC_KEY",
        // optional, default "0000000000000000000000000000000000000000000000000000000000000000"
        "preSharedKey": "PRE_SHARED_KEY",
        "endpoint": "ENDPOINT_ADDR",
        // optional, default 0
        "keepAlive": 0,
        // optional, default ["0.0.0.0/0", "::/0"]
        "allowedIPs": ["0.0.0.0/0"]
      }
    ],
    // optional, default 1420
    "mtu": 1420,
    // optional, default runtime.NumCPU()
    "workers": 2
  },
  // wireguard protocol are only available on udp connections, causes StreamSettings don't matter
  "streamSettings": {},
  "tag": "wireguard-1"
}
~~~   
compared to original config
~~~ini
[Interface]
PrivateKey = PRIVATE_KEY
Address = IPv4_CIDR
Address = IPv6_CIDR
MTU = 1420
[Peer]
PublicKey = PUBLIC_KEY
PreSharedKey = 0000000000000000000000000000000000000000000000000000000000000000
AllowedIPs = 0.0.0.0/0
Endpoint = ENDPOINT_ADDR
KeepAlive = 0
~~~

# Related issue
#705

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks for your work and fast fixes! I'm surprised that official wireguard-go doesn't compile on some of architectures. https://github.com/nanoda0523/wireguard/commit/dc2e486eb585f15762ceeb2ebbbe1c9ed1e54097
 Are you going to send pr for wireguard-g Otherwise I can imagine it will be a burden to you to maintain a branch.
 I will do some test later.
Feel free to add comments @nekohasekai

**Comment by nanoda0523** [comment]
> Thanks for your work and fast fixes! I'm surprised that official wireguard-go doesn't compile on some of architectures. [nanoda0523/wireguard@dc2e486](https://github.com/nanoda0523/wireguard/commit/dc2e486eb585f15762ceeb2ebbbe1c9ed1e54097) Are you going to send pr for wireguard-go? Otherwise I can imagine it will be a burden to you to maintain a branch. I will do some test later. Feel free to add comments @nekohasekai

I will pull request the compile fix for os dragonfly, and i was thought that i somehow break something on openbsd support for architecture `arm` and `386`, but i don't have a device for testing out.    
There's a enum missing for these architectures, and i [replaced with its actual value](https://github.com/nanoda0523/wireguard/commit/dc2e486eb585f15762ceeb2ebbbe1c9ed1e54097#diff-f6bb675ba9b3c1c4b73dd6d7f86082b16d4e3c4db80ea2244c5703aba1f9ee9cR168), and these part of code don't affect my code in this pr.   
   
I can transfer the repository to your account or this organization anyway.

sorry for bad english, my native not english either chinese :(

**Comment by nanoda0523** [comment]
> @nanoda0523 fantastic work!
> 
> there is a branch for ported [dragonfly and openbsd](https://git.zx2c4.com/wireguard-go/tree/?h=bo/dflybsd-port) in the official repository, is it possible we import it here?
> 
> relates to [WireGuard/wireguard-go#49](https://github.com/WireGuard/wireguard-go/pull/49)

thanks for pointing me out these was already a port for that :)

but... the official port was from 2018 and may have missing features or security issues compares with the latest one, and it seems have breaking changes in api    
shall we drop updates from 2018?

[the pull request](https://github.com/WireGuard/wireguard-go/pull/49) still not working on openbsd(386 and arm), but only the error code missing, i will take the code

**Comment by nekohasekai** [comment]
Some versions of gVisor have compatibility issues.

The implementation in sing-box is available for reference: https://github.com/SagerNet/sing-box/blob/dev-next/outbound/wireguard.go

**Comment by nanoda0523** [comment]
I will switch to sagerget/wireguard-go instead of my fork if [this pull request](https://github.com/SagerNet/wireguard-go/pull/1) has merged.   
it provides compatibility for openbsd and dragonfly that useful for this pr.   

If that pull request got rejected, i can transfer the repository to wherever trustworthy for users.

**Comment by yuhan6665** [comment]
Sounds like the best option.
 I still think we should try pull into official wireguard-go but in the mean time we can help you maintaining branch @nekohasekai

**Comment by yuhan6665** [comment]
Don't worry. There is a recent flaky test TestDOHNameServer I haven't got a chance to fix. You can ignore it.
Give me some time to do a manual test, if I don't see any issue I will merge. Thanks!

**Comment by yuhan6665** [comment]
@nanoda0523 for sure we can include it as well. Haven't got a chance to look into it deeply. If understand correct, it is for client -> vps -> warp scenario and client won't need to open two apps. Take a look at dailerProxy under streamsettings, I think that is the recommended approach now.

**Comment by yuhan6665** [comment]
@nanoda0523 I think idea is the same, just one config from Xray dev and one config from v2fly community

**Comment by yuhan6665** [comment]
@nanoda0523 I did some test on my environment, it works pretty well. I have a few comments:

- Currently it give error when `endpoint` is domain address (Eg, engage.cloudflareclient.com:2408). Can we support it by adding a dns lookup?
- For local address wg0:
```
    "address": [
      "IPv4_CIDR",
      "IPv6_CIDR",
      "and more..."
    ],
```
Do you think it is possible to hard code a default value? I understand it just need a local addr for Tun, and a default value like 
```
Address = 172.16.0.2/32
Address = 2606:4700:110:8949:fed8:2642:a640:c8e1/128
```
should work in most use case.
- I tested dialer proxy on the client side (connect to a normal vless/shadowsocks proxy server and forward to warp). It works, but for some reason the bandwidth is very slow. I feel like there is a bug. If you have time you can take a look. But don't worry if we can't fix it now - I intended to write a tutorial and ask more people to test it.

**Comment by yuhan6665** [comment]
@nanoda0523 can you do me another favor to resolve the minor conflict? I will merge later.

**Comment by yuhan6665** [comment]
I think in the go mod file, try rebase on latest main you should see

**Comment by yuhan6665** [comment]
Nevermind I think I can squash

**Comment by yuhan6665** [comment]
Thanks again! I'll try dailer again, maybe something wrong on my device or config

**Comment by yuhan6665** [comment]
@nanoda0523 I tried again with barebone config [here](https://xtls.github.io/document/level-2/warp.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8-warp-%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86) Still has slow issue with it. How do you config dialer proxy?

**Comment by kdurov** [comment]
Can someone else please confirm if there's performance issue with this implementation of wireguard?
I have the same issue as @yuhan6665 

It can hardly reach 20% of my local fiber port speed compared to full speed from manual wireguard connection in Debian.
Multiple thread downloading can however saturate my local port speed but single thread is somehow "capped" at around 20Mbps.

**Comment by kdurov** [comment]
still same throttled ul dl rate on ver. 1.6.6

**Comment by xhsnalii** [comment]
> still same throttled ul dl rate on ver. 1.6.6

yes same problem speed is very slow.

**Pull request merged**
