### PR TITLE
Add Libertea to web panel list

### PR DESCRIPTION
**Pull request by VZiChoushaDui**

### CODE REVIEW

**Comment by RPRX** [comment]
WSS 可以一眼识别，建议加上 gRPC

**Comment by VZiChoushaDui** [comment]
We currently use specific websocket URLs (and reroute them through haproxy to actual X-Ray process) for individual user management and limiting.

Can you think of any way to achieve the same result on a single port for gRPC?

(Same thing with the new REALITY protocol, we're looking for ways to implement it without breaking user management)

**Comment by VZiChoushaDui** [comment]
Oh, just saw that gRPC configuration also works on a custom endpoint, and so it's probably doable to implement it on the same stack. Will look into it.

But the thing about REALITY remains, can you think of anything regarding this?

**Comment by RPRX** [comment]
Added.

**Pull request closed without merging**
