### PR TITLE
fix: When add feature will remove old one first

### PR DESCRIPTION
**Pull request by thank243**
Please check it, Maybe it have some data race.

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks!
How about keep the AddFeature() as is, but add a new method called ReplaceFeature()? Also, can you post some reference code or document how would you use this new method?

**Comment by thank243** [comment]
IMO, Only one each of `feature.Type` can exist in `instance.features`. Otherwise add same types into `instance.features` the latest `feature` will never be used. https://github.com/XTLS/Xray-core/blob/11ec77bc768a07a727d5f5836aa9fe4c8e20421c/core/xray.go#L37-L44
To ensure Xray instance works properly, the config must contain one Dispatcher, one InboundHandlerManager and one OutboundHandlerManager. Other features are optional. I could totally add optional features after core started up.
For example, I can add dns feature after core started up.
```go
	dnsInstance, err := serial.ToTypedMessage(dnsConfig).GetInstance()
	if err != nil {
		return err
	}
	obj, err := core.CreateObject(c.server, dnsInstance)
	if err != nil {
		return err
	}
	if feature, ok := obj.(features.Feature); ok {
		c.server.AddFeature(feature)
	}
```

**Comment by thank243** [comment]
Hello @yuhan6665 , This PR seems have some problems. I'm confused with this codes. Could you tell the mechanism？
https://github.com/XTLS/Xray-core/blob/11ec77bc768a07a727d5f5836aa9fe4c8e20421c/app/dispatcher/default.go#L103-L107
Where is the ` dc dns.Client` come from? And how can I pass it?

**Comment by yuhan6665** [comment]
I see. I don't think there are bug with the current AddFeature(). The config should have only one feature with the same type and the check here
https://github.com/XTLS/Xray-core/blob/11ec77bc768a07a727d5f5836aa9fe4c8e20421c/core/xray.go#L220-L224
Ensure there will not be more than one feature of the same type.

**Comment by thank243** [comment]
> I see. I don't think there are bug with the current AddFeature(). The config should have only one feature with the same type and the check here
> 
> https://github.com/XTLS/Xray-core/blob/11ec77bc768a07a727d5f5836aa9fe4c8e20421c/core/xray.go#L220-L224
> 
> 
> Ensure there will not be more than one feature of the same type.

You are right. But when 3rd project quote this method could cause some problems. AddFeature is a public method. But it is not very important, so I closed this PR.

**Pull request closed without merging**
