### PR TITLE
feat: rate limit

### PR DESCRIPTION
**Pull request by AkinoKaede**
Related Issues: #415 
  
```jsonc
"policy": {
    "levels": {
        "0": {
            "uplinkSpeed": "10M", // M=Mbps
            "downlinkSpeed": "10M"
         },
        "1": {
            "uplinkSpeed": "100M",
            "downlinkSpeed": "100M"
         }
    }
},
```
```jsonc
{
    "vnext": [
        {
            "address": "127.0.0.1",
            "port": 37192,
            "users": [
                {
                    "id": "17f8d4ab-1a44-4f27-a6a9-3ebec510efc5",
                    "level": 0
                },
                {
                    "id": "04d38505-888e-491c-af6a-b16a6d4ea09a",
                    "level": 1         
               }
            ]
        }
    ]
}
```
**TODO**

- [ ] Add to other inbounds
- [x] Rename configurations

### CODE REVIEW

**Comment by JimhHan** [comment]
`upLinkSpeed` `downLinkSpeed` ？

**Comment by AkinoKaede** [comment]
> `upLinkSpeed` `downLinkSpeed` ？

我觉得这个不错

**Comment by AkinoKaede** [comment]
目前把 Limiter 放到 MemoryUser 里面可能不太好，也不方便加到其他代理协议，有什么建议吗

**Comment by JimhHan** [comment]
@AkinoKaede Level？

**Comment by crossfw** [comment]
有一个小问题，当上行限速时，比如使用网页测速，在上行测速完成后，仍有流量通过(不管实际网速是否大于限速值)

正常情况下的测速
image

使用 Xray 限速 1000M 之后的测速
image

使用 Xray 限速 10M 之后的测速
image

环境 win10 + [Github action 编译的限速版本](https://github.com/XTLS/Xray-core/actions/runs/692155133)

添加的 level=2 的用户配置是
```json
"2": {
                "handshake": 4,
                "connIdle": 10,
                "uplinkOnly": 0,
                "downlinkOnly": 0,
                "uplinkSpeed": "1000M",
                "downlinkSpeed": "1000M",
                "statsUserDownlink": true,
                "statsUserUplink": true
            }
```

使用 API 添加了一个 vmess+tcp 入站。

**Comment by laoshan-taoist** [comment]
插眼关注一下

**Comment by AkinoKaede** [comment]
> 有一个小问题，当上行限速时，比如使用网页测速，在上行测速完成后，仍有流量通过(不管实际网速是否大于限速值)
> 
> 正常情况下的测速
> image
> 
> 使用 Xray 限速 1000M 之后的测速
> image
> 
> 使用 Xray 限速 10M 之后的测速
> image
> 
> 环境 win10 + [Github action 编译的限速版本](https://github.com/XTLS/Xray-core/actions/runs/692155133)
> 
> 添加的 level=2 的用户配置是
> 
> ```json
> "2": {
>                 "handshake": 4,
>                 "connIdle": 10,
>                 "uplinkOnly": 0,
>                 "downlinkOnly": 0,
>                 "uplinkSpeed": "1000M",
>                 "downlinkSpeed": "1000M",
>                 "statsUserDownlink": true,
>                 "statsUserUplink": true
>             }
> ```
> 
> 使用 API 添加了一个 vmess+tcp 入站。

可能是这些流量在 500ms 之内拿到了 Tickets，所以测速停止后依然被写入，试试修改下面那个数值。
https://github.com/XTLS/Xray-core/blob/c786e978524febd8a9a231c8cc4267e0c28564cb/app/dispatcher/bucket.go#L19

**Comment by AkinoKaede** [comment]
I think we don't need this now.

**Comment by arinc9** [comment]
@AkinoKaede could you rebase this to the latest xray-core or, preferably, v2ray-core?

**Comment by chart41** [comment]
Guys. I don't understand, is it possible to limit user's bandwith or not?
I tryied to add this [code](https://github.com/XTLS/Xray-core/pull/444#issue-842076713) to my confing, but it seems doesn't work

**Comment by arinc9** [comment]
@chart41 v2fly's v2ray-core does not support it at the moment. But you can do it with Linux traffic control. I've created a page for it. Check the link below.

https://arinc9.com/arinc9/Limit-download-upload-rate-of-v2ray-user-with-Linux-traffic-control-1624a85a866980fcb8ebf0138e43bf88

**Comment by chart41** [comment]
> @chart41 v2fly's v2ray-core does not support it at the moment. But you can do it with Linux traffic control. I've created a page for it. Check the link below.
> 
> https://arinc9.com/arinc9/Limit-download-upload-rate-of-v2ray-user-with-Linux-traffic-control-1624a85a866980fcb8ebf0138e43bf88

Hello. Thanks for answering.
So every user should be connected to different port?

**Comment by arinc9** [comment]
Yes.

**Pull request closed without merging**
