### PR TITLE
Add sniff protocols: BGP, SMB, RDP, SIP, OpenVPN, SSH, NTP, RTSP

### PR DESCRIPTION
**Pull request by MrRanMao**
I added additional protocols to the sniffer configuration to better and more conveniently distribute traffic between different outbound based on protocols

Added protocols:
- BGP
- SMB
- RDP
- SIP
- OpenVPN
- SSH
- NTP
- RTSP

### CODE REVIEW

**Comment by Fangliding** [comment]
Are you sure these protocols have been tested and can work? The test file looks strange
Some of the protocols in the list are also confused me (BGP? SIP?)
Why add them to destoverride? Do you understand what it does?

**Comment by Kittyskj** [comment]
做得很好，添加了这些新的协议！这将显著改善流量分配并使管理更加高效。感谢你的贡献！

**Comment by yuhan6665** [comment]
Agree with Famgliding. We need to focus this project. Xray has one simple goal, to bypass gfw. Why do you need to sniff these protocols?
It is likely more suitable for openGFW project

**Comment by Fangliding** [comment]
> > Agree with Fangliding. We need to focus this project. Xray has one simple goal, to bypass gfw. Why do you need to sniff these protocols? It is likely more suitable for openGFW project
> 
> 让我们面对现实吧，这个项目早已不仅仅是为了绕过openGFW。它现在更像是一个用于绕过DPI和防火墙的安全VPN协议。正是他们展示的这些内容，才是我们改进这项技术所需要的。我完全不同意开发者和你们的看法，这更像是那句俗语‘得过且过’。如果你们不从多方面推动项目发展，那就是在吃闲饭。

To "尊敬的反审查专家"
1 xray是一个软件 不是什么 "安全VPN协议" 也不是"绕过**openGFW**的"
2 饭都没得吃哪来吃闲饭
3 群里talk过之后觉得代码过于奇怪有点像AI写的 发长篇大论前麻烦自己review一下评论和代码

**Comment by Kittyskj** [comment]
> > > Agree with Fangliding. We need to focus this project. Xray has one simple goal, to bypass gfw. Why do you need to sniff these protocols? It is likely more suitable for openGFW project
> > 
> > 
> > 让我们面对现实吧，这个项目早已不仅仅是为了绕过openGFW。它现在更像是一个用于绕过DPI和防火墙的安全VPN协议。正是他们展示的这些内容，才是我们改进这项技术所需要的。我完全不同意开发者和你们的看法，这更像是那句俗语‘得过且过’。如果你们不从多方面推动项目发展，那就是在吃闲饭。
> 
> To "尊敬的反审查专家" 1 xray是一个软件 不是什么 "安全VPN协议" 也不是"绕过**openGFW**的" 2 饭都没得吃哪来吃闲饭 3 群里talk过之后觉得代码过于奇怪有点像AI写的 发长篇大论前麻烦自己review一下评论和代码
> 
> 所以莫争了 OK 如果觉得有用的人多（比如ssh好像有点反响）那确实会考虑的

即使项目只是作为一种绕过的方式，很多人也把它当作VPN来用。这是第一点。第二点，如果你创建了一个开源项目，就应该考虑到不会有人付钱给你。现在人工智能已经比人类聪明，讨论代码的好坏已经没有意义了。你自己和你的团队再好好看看代码吧。我不该争论？那我要怎么捍卫我的观点呢？你们就像井底之蛙一样。像个孩子似的，拿出来好好看看，然后接受它。

**Comment by yuhan6665** [comment]
I think elephant in the room is the feature owner want to block it when his user is using these protocols. Which if you think about it, is against the purpose of Xray

**Pull request closed without merging**
