### PR TITLE
feat: metrics including pprof and expvars

### PR DESCRIPTION
**Pull request by yichya**
A more straightforward (and hopefully better) way to export stats.

# Enabling metrics

Quite similar to how to enable Xray APIs

1. Add a top-level configuration called `metrics` with `tag` (outbound tag) as its only configuration
  ```json
  {
      "metrics": {
          "tag": "metrics_out"
      }
  }
  ```
2. Add a dokodemo door inbound. For example here we use `127.0.0.1:11111`
  ```json
  {
      "port": 11111,
      "protocol": "dokodemo-door",
      "tag": "metrics_in",
      "settings": {
          "address": "127.0.0.1"
      },
      "listen": "127.0.0.1"
  }
  ```
3. Use routing to connect them together
  ```json
  {
      "type": "field",
      "inboundTag": [
          "metrics_in"
      ],
      "outboundTag": "metrics_out"
  }
  ```

# Usage

## pprof

Access `http://127.0.0.1:11111/debug/pprof/` or use `go tool pprof` to start profiling or inspect running goroutines.

## expvars

Access `http://127.0.0.1:11111/debug/vars`

Variables exported include: 

* `stats` includes statistics about inbounds, outbounds and users
* `observatory` includes observatory results

for example with [luci-app-xray](https://github.com/yichya/luci-app-xray) you are likely to get a result like this (standard expvar things like `cmdline` and `memstats` are omitted)

<details>

```json
{
    "observatory": {
        "tcp_outbound": {
            "alive": true,
            "delay": 782,
            "outbound_tag": "tcp_outbound",
            "last_seen_time": 1648477189,
            "last_try_time": 1648477189
        },
        "udp_outbound": {
            "alive": true,
            "delay": 779,
            "outbound_tag": "udp_outbound",
            "last_seen_time": 1648477191,
            "last_try_time": 1648477191
        }
    },
    "stats": {
        "inbound": {
            "api": {
                "downlink": 0,
                "uplink": 0
            },
            "dns_server_inbound_5300": {
                "downlink": 14286,
                "uplink": 5857
            },
            "http_inbound": {
                "downlink": 74460,
                "uplink": 10231
            },
            "https_inbound": {
                "downlink": 0,
                "uplink": 0
            },
            "metrics": {
                "downlink": 6327,
                "uplink": 1347
            },
            "socks_inbound": {
                "downlink": 19925615,
                "uplink": 5512
            },
            "tproxy_tcp_inbound": {
                "downlink": 4739161,
                "uplink": 1568869
            },
            "tproxy_udp_inbound": {
                "downlink": 0,
                "uplink": 2608142
            }
        },
        "outbound": {
            "blackhole_outbound": {
                "downlink": 0,
                "uplink": 0
            },
            "direct": {
                "downlink": 97714548,
                "uplink": 3234617
            },
            "dns_server_outbound": {
                "downlink": 7116,
                "uplink": 2229
            },
            "manual_tproxy_outbound_tcp_1": {
                "downlink": 0,
                "uplink": 0
            },
            "manual_tproxy_outbound_udp_1": {
                "downlink": 0,
                "uplink": 0
            },
            "tcp_outbound": {
                "downlink": 23873238,
                "uplink": 1049595
            },
            "udp_outbound": {
                "downlink": 639282,
                "uplink": 74634
            }
        },
        "user": {}
    }
}
```

</details>

To get a better view of these numbers, [Netdata](https://github.com/netdata/netdata) (with python.d plugin) is a great option:

1. Edit related configuration file (`sudo /etc/netdata/edit-config python.d/go_expvar.conf`)
2. Take the following configuration file as an example:

<details>

```yaml
xray:
  name: 'xray'
  update_every: 2
  url: 'http://127.0.0.1:11111/debug/vars'
  collect_memstats: false
  extra_charts:
     - id: 'inbounds'
       options:
         name: 'inbounds'
         title: 'Xray System Inbounds'
         units: bytes
         family: xray
         context: xray.inbounds
         chart_type: line
       lines:
         - expvar_key: stats.inbound.tproxy_tcp_inbound.downlink
           id: 'tcp.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.tproxy_udp_inbound.downlink
           id: 'udp.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.http_inbound.downlink
           id: 'http.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.https_inbound.downlink
           id: 'https.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.socks_inbound.downlink
           id: 'socks.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.tproxy_tcp_inbound.uplink
           id: 'tcp.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.tproxy_udp_inbound.uplink
           id: 'udp.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.http_inbound.uplink
           id: 'http.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.https_inbound.uplink
           id: 'https.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.inbound.socks_inbound.uplink
           id: 'socks.uplink'
           algorithm: incremental
           expvar_type: int
     - id: 'outbounds'
       options:
         name: 'outbounds'
         title: 'Xray System Outbounds'
         units: bytes
         family: xray
         context: xray.outbounds
         chart_type: line
       lines:
         - expvar_key: stats.outbound.tcp_outbound.downlink
           id: 'tcp.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.outbound.udp_outbound.downlink
           id: 'udp.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.outbound.direct.downlink
           id: 'direct.downlink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.outbound.tcp_outbound.uplink
           id: 'tcp.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.outbound.udp_outbound.uplink
           id: 'udp.uplink'
           algorithm: incremental
           expvar_type: int
         - expvar_key: stats.outbound.direct.uplink
           id: 'direct.uplink'
           algorithm: incremental
           expvar_type: int
     - id: 'observatory'
       options:
         name: 'observatory'
         title: 'Xray Observatory Metrics'
         units: milliseconds
         family: xray
         context: xray.observatory
         chart_type: line
       lines:
         - expvar_key: observatory.tcp_outbound.delay
           id: tcp
           expvar_type: int
         - expvar_key: observatory.udp_outbound.delay
           id: udp
           expvar_type: int
```

</details>

And you will get a nice plot like this:

image

# Additional

Maybe reusing the empty object `stats` in config file is better than adding `metrics` here?

**Edit:** removed prometheus related things and added usage about expvars

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks for your great effort! It seems to me the code is well written.
However, as you can see, *ray core has been very cautious on adding more external libraries. Our project is sensitive and we need to be careful not to bring weakness from other sources. More importantly, note that core is used on both client and server sides, used in servers, desktops, phones and routers. The question we need to answer is: are the dependency belong to the "core" feature? Is the feature useful to all platforms?
Maybe, this feature is more suitable for https://github.com/XrayR-project/XrayR or https://github.com/vaxilu/x-ui

I'm curious to hear what other project participants think about this.

**Comment by yichya** [comment]
Added metrics about observatory (with `xray_observatory{outbound=~".+"}`, values in seconds)

image

**Comment by yichya** [comment]
@yuhan6665 

Thank you for your reply.

> However, as you can see, *ray core has been very cautious on adding more external libraries. Our project is sensitive and we need to be careful not to bring weakness from other sources. 

Prometheus client has been widely used in many projects, including similar anti-censorship tools like [hysteria](https://github.com/HyNetwork/hysteria/blob/master/go.mod#L19). It does not do more than formatting some numbers to a specific format so I don't assume that would be too vulnerable.

If you are really concerned about involving external dependencies I could add only `expvars` and `pprof` and expose these metrics using `expvars`. They are included in go standard library and no external dependency is needed. Prometheus format could be then converted from `expvars` via a external formatter.

> More importantly, note that core is used on both client and server sides, used in servers, desktops, phones and routers. The question we need to answer is: are the dependency belong to the "core" feature? Is the feature useful to all platforms?

Personally I think observability as a feature is

* useful to normal users willing to know whether things are working as expected (for example to see bandwidth usage of their outbounds)
* important to power users and mass service providers (to know more about resource consumption and solve performance issues)

Even if you don't need that feature, you could just turn it off and it won't do any harm at all.

**Comment by yichya** [comment]
I've removed prometheus related code from my commit. That part could be discussed later as another merge request.

**Comment by yuhan6665** [comment]
Thanks for the update! I will do some test on my side tomorrow and update you if I see anything need change.

**Comment by yichya** [comment]
Added some more detailed description about `expvars` and its usage.

**Comment by yuhan6665** [comment]
Looks great to me! Thanks for your work and thorough documentation!

**Comment by lemchen** [comment]
i seems not working on xray 1.5.5, no data flows, when i use netdata.

**Comment by lemchen** [comment]
> i seems not working on xray 1.5.5, no data flows, when i use netdata.
> 
> curl http://127.0.0.1:11111/debug/vars `{ "cmdline": ["/usr/local/bin/xray","run","-config","/usr/local/etc/xray/config.json"], "memstats": {"Alloc":14907856,"TotalAlloc":226313112,"Sys":90394648,"Lookups":0,"Mallocs":1122204,"Frees":816217,"HeapAlloc":14907856,"HeapSys":78970880,"HeapIdle":62865408,"HeapInuse":16105472,"HeapReleased":62767104,"HeapObjects":305987,"StackInuse":720896,"StackSys":720896,"MSpanInuse":192712,"MSpanSys":783360,"MCacheInuse":4800,"MCacheSys":15600,"BuckHashSys":1474066,"GCSys":7528040,"OtherSys":901806,"NextGC":29763664,"LastGC":1651545906656014879,"PauseTotalNs":2576020,"PauseNs":[108961,140202,159738,87092,112183,88647,95166,87647,90962,103091,130943,107444,128146,90444,133517,87517,130609,122164,142646,107609,258237,63055,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1651545904995702657,1651545905009957744,1651545905332494359,1651545905343213299,1651545905361973130,1651545905372454259,1651545905395337709,1651545905412840596,1651545905431018732,1651545905471650825,1651545905485490364,1651545905524202061,1651545905581004340,1651545905612953145,1651545905671573655,1651545905711093728,1651545905846292665,1651545905994517893,1651545906242722323,1651545906513199917,1651545906633788901,1651545906656014879,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":22,"NumForcedGC":12,"GCCPUFraction":0.04789582830192134,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":1315,"Frees":673},{"Size":16,"Mallocs":511445,"Frees":271730},{"Size":24,"Mallocs":83880,"Frees":32960},{"Size":32,"Mallocs":68571,"Frees":59652},{"Size":48,"Mallocs":10245,"Frees":8116},{"Size":64,"Mallocs":17733,"Frees":17104},{"Size":80,"Mallocs":21448,"Frees":21145},{"Size":96,"Mallocs":307000,"Frees":306619},{"Size":112,"Mallocs":971,"Frees":681},{"Size":128,"Mallocs":890,"Frees":563},{"Size":144,"Mallocs":510,"Frees":206},{"Size":160,"Mallocs":261,"Frees":86},{"Size":176,"Mallocs":11950,"Frees":11732},{"Size":192,"Mallocs":45,"Frees":29},{"Size":208,"Mallocs":259,"Frees":76},{"Size":224,"Mallocs":15,"Frees":7},{"Size":240,"Mallocs":18,"Frees":2},{"Size":256,"Mallocs":93,"Frees":56},{"Size":288,"Mallocs":144,"Frees":85},{"Size":320,"Mallocs":65,"Frees":57},{"Size":352,"Mallocs":94,"Frees":45},{"Size":384,"Mallocs":78,"Frees":8},{"Size":416,"Mallocs":121,"Frees":23},{"Size":448,"Mallocs":84,"Frees":3},{"Size":480,"Mallocs":21,"Frees":4},{"Size":512,"Mallocs":116,"Frees":106},{"Size":576,"Mallocs":70,"Frees":34},{"Size":640,"Mallocs":73,"Frees":46},{"Size":704,"Mallocs":35,"Frees":13},{"Size":768,"Mallocs":18,"Frees":4},{"Size":896,"Mallocs":76,"Frees":55},{"Size":1024,"Mallocs":74,"Frees":46},{"Size":1152,"Mallocs":40,"Frees":16},{"Size":1280,"Mallocs":62,"Frees":20},{"Size":1408,"Mallocs":18,"Frees":10},{"Size":1536,"Mallocs":7,"Frees":3},{"Size":1792,"Mallocs":36,"Frees":11},{"Size":2048,"Mallocs":57,"Frees":43},{"Size":2304,"Mallocs":17,"Frees":5},{"Size":2688,"Mallocs":30,"Frees":4},{"Size":3072,"Mallocs":9,"Frees":5},{"Size":3200,"Mallocs":3,"Frees":0},{"Size":3456,"Mallocs":2,"Frees":0},{"Size":4096,"Mallocs":53,"Frees":45},{"Size":4864,"Mallocs":8,"Frees":5},{"Size":5376,"Mallocs":8,"Frees":0},{"Size":6144,"Mallocs":11,"Frees":5},{"Size":6528,"Mallocs":0,"Frees":0},{"Size":6784,"Mallocs":21,"Frees":21},{"Size":6912,"Mallocs":0,"Frees":0},{"Size":8192,"Mallocs":2917,"Frees":2900},{"Size":9472,"Mallocs":8,"Frees":3},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":14,"Frees":14},{"Size":10880,"Mallocs":1,"Frees":1},{"Size":12288,"Mallocs":5,"Frees":5},{"Size":13568,"Mallocs":6,"Frees":5},{"Size":14336,"Mallocs":9,"Frees":8},{"Size":16384,"Mallocs":9,"Frees":6},{"Size":18432,"Mallocs":1,"Frees":1}]}, "observatory": null, "stats": null }`

xray logged this:
`xray[33868]: 2022/05/03 14:48:45 127.0.0.1:51580 accepted tcp:127.0.0.1:0 [metrics_in -> metrics_out]`

**Comment by xyz3282836** [comment]
step 1 2 3 done
but observatory and stats is null

**Pull request merged**
