### PR TITLE
Add RESTful API

### PR DESCRIPTION
**Pull request by CerteKim**
## Configure
`"web":{}`  example
```
{
    "web":{
        "tag":"web",
        "api": {
            "address": "127.0.0.1",
            "port": 65434
        },
        "pprof": true
    }
}
```
`"tag"` : Outbound tag
`"address"` : gRPC server address, default `127.0.0.1`
`"port"` : gRPC server port, default `0` ( When 0, xray won't dial gRPC server )
`"pprof"` : turn on/off [pprof](https://github.com/google/pprof)

### Example

dokodemo-door inbound listening http request & gRPC api
```
{
    "inbounds": [
        {
            "tag": "api",
            "port": 65434,
            "listen": "127.0.0.1",
            "protocol": "dokodemo-door",
            "settings": {
                "udp": false,
                "address": "127.0.0.1",
                "allowTransparent": false
            }
        },
        {
            "tag": "web",
            "port": 65433,
            "listen": "127.0.0.1",
            "protocol": "dokodemo-door",
            "settings": {
                "address": "127.0.0.1"
            }
        }
    ],
    "api": {
        "tag": "api",
        "services": [
            "HandlerService",
            "LoggerService",
            "StatsService"
        ]
    },
    "policy": {
        "levels": {
            "0": {
                "handshake": 4,
                "connIdle": 300,
                "uplinkOnly": 2,
                "downlinkOnly": 5,
                "statsUserUplink": true,
                "statsUserDownlink": true,
                "bufferSize": 10240
            }
        },
        "system": {
            "statsInboundUplink": true,
            "statsInboundDownlink": true,
            "statsOutboundUplink": true,
            "statsOutboundDownlink": true
        }
    }
}
```

`"web":{}`
```
{
    "web":{
        "tag":"web",
        "api": {
            "address": "127.0.0.1",
            "port": 65434
        },
        "pprof": true
    }
}
```

routing trafic from inbound `web` to `"web"`
```
{
    "routing": {
        "rules": [
            {
                "inboundTag": [
                    "api"
                ],
                "outboundTag": "api",
                "type": "field"
            },
            {
                "type": "field",
                "inboundTag": [
                    "web"
                ],
                "outboundTag": "web"
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by CerteKim** [comment]
api uri:
1. GET: uri: `/api/xray/statssys`
    - return json
2. GET: uri: `/api/xray/statssys/:pattern`
    - return json
    - e.g. 
        - `curl "http://127.0.0.1:8080/api/xray/statsquery"`
            - return all
        - `curl "http://127.0.0.1:8080/api/xray/statsquery/outbound>>>proxy>>>traffic>>>downlink"`
            - return counter outbound>>>proxy>>>traffic>>>downlink
3. GET: uri: `/api/xray/stats/:name`
    - return json
        - e.g. `curl "http://127.0.0.1:8080/api/xray/stats/outbound>>>proxy>>>traffic>>>downlink"`
4. GET: uri: `/api/xray/inbound/remove/:tag`
5. GET: uri: `/api/xray/outbound/remove/:tag`
6. POST: uri: `/api/xray/inbound/add`, header: "Content-Type: application/json"
    - e.g.
```
    curl \
    --header "Content-Type: application/json" \
    --data '
    {
        "tag": "http-test",
        "port": 2080,
        "protocol": "http",
        "settings": {}
    }
    ' \
    http://127.0.0.1:8080/api/xray/inbound/add
```
7. POST: uri: `/api/xray/outbound/add`, header: "Content-Type: application/json"
    - e.g. 
```
curl \
    --header "Content-Type: application/json" \
    --data '
    {
        "tag": "proxy-test",
        "protocol": "VLESS",
        "settings": {
            "vnext": [
                {
                    "address": "192.168.1.1",
                    "port": 443,
                    "users": [
                        {
                            "id": "00000000-0000-0000-0000-000000000000",
                            "alterId": 0,
                            "email": "t@t.tt",
                            "security": "none",
                            "encryption": "none",
                            "flow": "xtls-rprx-splice"
                        }
                    ]
                }
            ],
            "servers": null,
            "response": null
        },
        "streamSettings": {
            "network": "tcp",
            "security": "xtls",
            "xtlsSettings": {
                "allowInsecure": false,
                "serverName": "foo.bar"
            }
        },
        "mux": {
            "enabled": false
        }
    }
    ' \
    http://127.0.0.1:8080/api/xray/outbound/add
```

**Review by AkinoKaede — CHANGES_REQUESTED** [review]
……RESTful 的话 应该是通过 HTTP Method 表示增删改查的  
| Method | CRUD |
|:-:|:-:|
|GET |Read|
|POST| Create |
| PUT/PATCH | Update |
| DELETE | Delete |
资源要用复数，比如 inbounds outbounds

**Comment by CerteKim** [comment]
已做一些修改 qwq

**Comment by smallprogram** [comment]
这个PR应该设立一个里程碑

**Comment by ku3333027** [comment]
> api uri:
> 
> 1. GET: uri: `/api/v1/xray/statssys`
>    
>    * return json
> 2. GET: uri: `/api/v1/xray/statssys/:pattern`
>    
>    * return json
>    * e.g.
>      
>      * `curl "http://127.0.0.1:8080/api/v1/xray/statsquery"`
>        
>        * return all
>      * `curl "http://127.0.0.1:8080/api/v1/xray/statsquery/outbound>>>proxy>>>traffic>>>downlink"`
>        
>        * return counter outbound>>>proxy>>>traffic>>>downlink
> 3. GET: uri: `/api/v1/xray/stats/:name`
>    
>    * return json
>      
>      * e.g. `curl "http://127.0.0.1:8080/api/v1/xray/stats/outbound>>>proxy>>>traffic>>>downlink"`
> 4. DELETE: uri: `/api/v1/xray/inbounds/:tag`
> 5. DELETE: uri: `/api/v1/xray/outbounds/:tag`
> 6. POST: uri: `/api/v1/xray/inbounds`, header: "Content-Type: application/json"
>    
>    * e.g.
> 
> ```
>     curl \
>     --header "Content-Type: application/json" \
>     --data '
>     {
>         "tag": "http-test",
>         "port": 2080,
>         "protocol": "http",
>         "settings": {}
>     }
>     ' \
>     http://127.0.0.1:8080/api/v1/xray/inbounds
> ```
> 
> 1. POST: uri: `/api/xray/v1/outbounds`, header: "Content-Type: application/json"
>    
>    * e.g.
> 
> ```
> curl \
>     --header "Content-Type: application/json" \
>     --data '
>     {
>         "tag": "proxy-test",
>         "protocol": "VLESS",
>         "settings": {
>             "vnext": [
>                 {
>                     "address": "192.168.1.1",
>                     "port": 443,
>                     "users": [
>                         {
>                             "id": "00000000-0000-0000-0000-000000000000",
>                             "alterId": 0,
>                             "email": "t@t.tt",
>                             "security": "none",
>                             "encryption": "none",
>                             "flow": "xtls-rprx-splice"
>                         }
>                     ]
>                 }
>             ],
>             "servers": null,
>             "response": null
>         },
>         "streamSettings": {
>             "network": "tcp",
>             "security": "xtls",
>             "xtlsSettings": {
>                 "allowInsecure": false,
>                 "serverName": "foo.bar"
>             }
>         },
>         "mux": {
>             "enabled": false
>         }
>     }
>     ' \
>     http://127.0.0.1:8080/api/v1/xray/outbounds
> ```

这个`>>>proxy>>>traffic>>>downlink` 请求格式能否换个格式。

**Comment by CerteKim** [comment]
@ku3333027 你想要更换成什么格式

**Comment by AkinoKaede** [comment]
URI 中的 xray 显得有些多余了，移除掉了

**Comment by ku3333027** [comment]
> @ku3333027 你想要更换成什么格式

User格式替换为:
```
{
    "email": "email@xxx.com",
    "up": 321,
    "down": 1111
}
```
Bound替换为:
```
[{
    "tag": "in",
    "type": "inbound",    // 如果URL上区分in还是out，这里可以不用返回。
    "up": 321,
    "down": 1111
},
{
    "tag": "out",
    "type": "outbound",    // 如果URL上区分in还是out，这里可以不用返回。
    "up": 321,
    "down": 1111
}] 

```


替换成这样的格式看起来更好一点，全JSON返回。
流量查询URL没必要区分上行或下行，大多用的都是上下行一起查询。

**Comment by CerteKim** [comment]
@ku3333027 本来的返回值就是 json。现在 api 请求格式是完全按照 gRPC 的 api 格式来做的，个人认为没有修改的必要

**Comment by CerteKim** [comment]
合并到另一个 pr 中

**Pull request closed without merging**
