### PR TITLE
update: Implement the proxy.UserManager of ss2022

### PR DESCRIPTION
**Pull request by thank243**
A first implements proxy.UserManager of shadowsocks2022
Considering implements shadowsocks2022 in xray-core may have better performance when crud users.
#1372

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks a lot for your work!
How do you test this new feature? Can you give a try for something like
https://github.com/crossfw/Xray-API-documents/blob/main/examples/alterInbound.go#L49

**Comment by thank243** [comment]
> Thanks a lot for your work! How do you test this new feature? Can you give a try for something like https://github.com/crossfw/Xray-API-documents/blob/main/examples/alterInbound.go#L49

Hello @yuhan6665 , I have tested on XrayR to invoke this interface. Its working normally. But when CURD user, it could have some performance problem. The ss2022 on sagernet haven't the remove user interface. Thus the implements just update all users when one user delete or add.

**Comment by yuhan6665** [comment]
I see you are using UpdateUsersWithPasswords(). Currently Xray rely on sing-ss implementation. I think the simplest way is to add the following interface in sing-ss:

- AddUserWithPassword()
- RemoveUser()

This way, update a single user would not require lopp through the whole list and recreate every user again.
CC @nekohasekai 

I'm not familiar with XrayR. Is it in the end call AlterInbound() -> AddUserOperation() ?

**Comment by thank243** [comment]
> I see you are using UpdateUsersWithPasswords(). Currently Xray rely on sing-ss implementation. I think the simplest way is to add the following interface in sing-ss:
> 
> * AddUserWithPassword()
> * RemoveUser()
> 
> This way, update a single user would not require loop through the whole list and recreate every user again. CC @nekohasekai
> 
> I'm not familiar with XrayR. Is it in the end call AlterInbound() -> AddUserOperation() ?

Yes, you are right. Add this interface is a good way by sing-ss. XrayR directly use proxy.UserManager interface to add or remove user. 

https://github.com/XrayR-project/XrayR/blob/212f0ff13591a263753dbc9b5e4962deaa61d1b8/service/controller/control.go#L58-L106

**Comment by yuhan6665** [comment]
Since XrayR can make direct call, another option is to add "AddMultiUsers" and "RemoveMultiUsers" in core. That should also help to some degree.
Anyways, I think this is a great starting point. Hope to see more improvements in this area :) Thanks again!

**Comment by nekohasekai** [comment]
If users need to be added or removed at runtime, synchronization locks must be used, which incurs a performance penalty.

**Comment by thank243** [comment]
> If users need to be added or removed at runtime, synchronization locks must be used, which incurs a performance penalty.

So can we use sync.map to reduce impact on performance？

**Comment by vangork** [comment]
@thank243 [XrayR](https://github.com/XrayR-project/XrayR) seems to implement another approach for online user management which doesn't align with the way of xray ifself. Can you also help to add a PR for `alterinbound` approach?

**Comment by thank243** [comment]
https://github.com/XrayR-project/XrayR/blob/master/service/controller/userbuilder.go#L89-L97

**Comment by vangork** [comment]
@thank243 it dosen't seem to support alterinboundrequest adduseroperation ss2022 server side. it fails with the error msg of `desc = app/proxyman/command: proxy is not a UserManager`

**Comment by thank243** [comment]
Only `type MultiUserInbound struct` implemented userManager. You should confirm the inbound handler is that.

**Pull request merged**
