### PR TITLE
update: release.yml

### PR DESCRIPTION
**Pull request by thank243**
refactor download *.dat files. I test it on my repo, works normally

### CODE REVIEW

**Comment by yuhan6665** [comment]
This looks great! Do you think it is possible to add the hash verification step with this approach? You understand that this project is quite sensitive and we need to ensure best security practice are followed.

**Comment by thank243** [comment]
Of course. I'll add it.

**Comment by yuhan6665** [comment]
The build time is back to normal. This is beautiful. Thanks so much!

**Comment by thank243** [comment]
I just fixing some bugs...LOL

**Pull request merged**
