### PR TITLE
新增功能支持

### PR DESCRIPTION
**Pull request by S-Mocking**
1.针对macos系统，增加入口pf，支持接收macos系统 pf防火墙转发过来的消息
2.重新启用部分出入口vless、vmess、socks、freedom、dokodemo、pf(本次新增入口)的timeout参数，来控制TCP链接超时时间，不配置默认使用300s或者600s（保持现有逻辑）,在xray应用与内部之间系统代理执行长事物时有此需求应用场景

增加pf入口配置demo如下：
{
  "inbounds": [
    {
      "tag": "all-in",
      "port": 1234,
      "protocol": "pf",
      "settings": {
        "network": "tcp",
        "followRedirect": true,
        "timeout": 7200,
        "userLevel": 0
      }
    }
  ],
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {}
  ]
}

### CODE REVIEW

**Comment by S-Mocking** [comment]
Is pf really a protocol? How do you configure it and why dokodemo doesn't work for you?
reply:
1.pf is the outbound protocol of FreeBSD port forwarding, similar to the relationship between iptables port forwarding and dokodemo
2.Because the MacOS firewall uses FreeBSD, the receiving end of this firewall needs to read the /dev/pf device to obtain the destination address and port when forwarding traffic. dokodemo does not support this part, so dokodemo cannot meet the requirements.


Tcp timeout should be part of the "streamsettings" -> take a look at tcp settings under Sockopt
reply:
Do you recommend setting the timeout parameter in "streamsettings"?

Consider making smaller pull request for one feature separately
reply:
What changes can I make to this?

**Comment by S-Mocking** [comment]
FreeBSD configures transparent agents on MacOS as follows:

1.Create a new file ～/config/pf.conf with the following contents:
scrub-anchor "com.apple/*"

#Define table
table <direct_cidr> persist file "/usr/local/etc/direct_cidr.conf"
table <direct_src> persist file "/usr/local/etc/direct_src.conf"

nat-anchor "com.apple/*"

#Forward all traffic on lo0 whose destination is not in the direct address list to the Xray pf listening address 127.0.0.1:1234
rdr pass on lo0 proto tcp from any to !<direct_cidr> -> 127.0.0.1 port 1234

rdr-anchor "com.apple/*"

#Route all traffic of en0 whose destination is not in the direct address list to lo0
pass out on en0 route-to (lo0 127.0.0.1) proto tcp from !<direct_src> to !<direct_cidr> keep state queue std

dummynet-anchor "com.apple/*"
anchor "com.apple/*"
load anchor "com.apple" from "/etc/pf.anchors/com.apple"


2.Execute command:
sudo pfctl -e && sudo pfctl -F all && sudo pfctl -f ～/config/pf.conf

3.xray logs
2022/08/18 18:13:26 192.168.20.139:61649 accepted tcp:13.225.142.125:443 [pf-in >> proxy]
2022/08/18 18:13:27 192.168.20.139:61651 accepted tcp:13.225.142.125:443 [pf-in >> proxy]
2022/08/18 18:13:28 192.168.20.139:61653 accepted tcp:13.225.142.125:443 [pf-in >> proxy]
2022/08/18 18:13:29 192.168.20.139:61655 accepted tcp:13.225.142.125:443 [pf-in >> proxy]
2022/08/18 18:13:31 192.168.20.139:61657 accepted tcp:99.84.192.6:443 [pf-in >> proxy]
2022/08/18 18:13:31 192.168.20.139:61659 accepted tcp:99.84.192.6:443 [pf-in >> proxy]

**Comment by yuhan6665** [comment]
Thanks for your info. Now I understand a bit more about pf. Essentially it is the similar port forwarding traffic with special way to read the destination address. I would propose the following:
Instead of adding a new protocol, you can add to "tproxy" option [here](https://xtls.github.io/config/transport.html#sockoptobject) 

tproxy option determine how to override the dest address 
https://github.com/XTLS/Xray-core/blob/76638d793c4b48aa863e4ecc17c4a3b6b2915a4f/proxy/dokodemo/dokodemo.go#L89

In fact you can see we already have platform dependant code for "tproxy": "redirect"
https://github.com/XTLS/Xray-core/blob/ffc2f7c4e2f759d1040a620b2ba019476e6456d4/transport/internet/tcp/sockopt_freebsd.go#L1

**Comment by S-Mocking** [comment]
According to your suggestions, the corresponding modifications have been made
#1189

**Comment by yuhan6665** [comment]
合了https://github.com/XTLS/Xray-core/pull/1189 这个先关了

**Pull request closed without merging**
