### PR TITLE
add bindAddr for darwin

### PR DESCRIPTION
**Pull request by hossinasaadi**

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thank a lot for your pr! Though I have a question.. how do you use this bind address in sockopt?

**Comment by us254** [comment]
The bind address is not directly used in the socket options (sockopt). Instead, it's used in the `bindAddr` function to bind the socket to a specific IP address and port. After this binding, the address is implicitly utilized in subsequent system calls for network communication. The socket options `SO_REUSEADDR` and `SO_REUSEPORT` are set separately using the `unix.SetsockoptInt` function to allow the reusing of local addresses and ports.

**Comment by yuhan6665** [comment]
@us254 right, but how to activate this feature? I see a code block commented out by @RPRX some time ago..
https://github.com/XTLS/Xray-core/commit/c41a1a56fe1817c64c9f3fba337422577a4f9725

**Comment by us254** [comment]
```
// Assuming fd, address, and port are appropriately defined
// Set up the socket configurations
sockopt := &internet.SocketConfig{
	Tproxy: internet.SocketConfig_TProxy,
}

if dest.Address.Family().IsIP() {
	sockopt.BindAddress = dest.Address.IP()
	sockopt.BindPort = uint32(dest.Port)
}

if d.sockopt != nil {
	sockopt.Mark = d.sockopt.Mark
}

// Call the functions to bind address and set socket options
err := bindAddr(fd, sockopt.BindAddress, sockopt.BindPort)
if err != nil {
    return err
}

err = setReuseAddr(fd)
if err != nil {
    return err
}

err = setReusePort(fd)
if err != nil {
    return err
}

// Dial a system-level connection
tConn, err := internet.DialSystem(ctx, net.DestinationFromAddr(conn.RemoteAddr()), sockopt)
if err != nil {
	return err
}
defer tConn.Close()

writer = &buf.SequentialWriter{Writer: tConn}
tReader := buf.NewPacketReader(tConn)
requestCount++
tproxyRequest = func() error {
	defer func() {
		if atomic.AddInt32(&requestCount, -1) == 0 {
			timer.SetTimeout(plcy.Timeouts.DownlinkOnly)
		}
	}()
	if err := buf.Copy(tReader, link.Writer, buf.UpdateActivity(timer)); err != nil {
		return newError("failed to transport request (TPROXY conn)").Base(err)
	}
	return nil
}

}
}

```

**Comment by hossinasaadi** [comment]
@yuhan6665 , sorry for late reply, I have worked on a customized version of Xray for macOS and realized that the reuse port and reuse address did not work in Darwin, so I feel it may be helpful for the main repo. 
it can be used kinda like @us254 mentioned before.

**Comment by yuhan6665** [comment]
Ok let's merge this for now. Thanks all!

**Pull request merged**
